### ISSUE TITLE
can't set trades in trade shop

### ISSUE THREAD

**Issue by blablubbabcDEV** [Shopkeepers/Shopkeepers#139]
**Migrated from:** https://dev.bukkit.org/projects/shopkeepers/issues/130

**Originally posted by soopageek (May 6, 2013):** 

What steps will reproduce the problem?
1. Setting trades in a "trade" shop.
2.
3.What is the expected output? What do you see instead?
Should be able to place item from inventory in Shopkeeper Editor to establish the item you want to trade, for the item in the chest.Â  When you try to do it, the item pops back in your inventory before you can do it.What version of the product are you using?
1.13.2Do you have an error log of what happened?2013-05-05 22:35:41 [WARNING] [Shopkeepers] Task #113333 for Shopkeepers v1.13.2 generated an exception
java.util.ConcurrentModificationException
at java.util.HashMap$HashIterator.remove(Unknown Source)
at com.nisovin.shopkeepers.ShopkeepersPlugin$4.run(ShopkeepersPlugin.java:583)
at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftTask.run(CraftTask.java:53)
at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:513)
at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:226)
at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:477)
at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:410)
at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)Please provide any additional information below.

**Comment by blablubbabcDEV** [comment]
**Originally commented by soopageek (May 6, 2013):** 

I'll add that, you CAN make it work if you do it REALLY fast before it pops back into your inventory.  But it's not working properly like it was before.

**Comment by blablubbabcDEV** [comment]
**Originally commented by nisovin (May 10, 2013):** 

Read the 1.13 change log.

**Comment by blablubbabcDEV** [comment]
**Originally closed by nisovin (Jul 5, 2013)**
