### ISSUE TITLE
Shopkeepers v1.13.2 generated an exception

### ISSUE THREAD

**Issue by blablubbabcDEV** [Shopkeepers/Shopkeepers#140]
**Migrated from:** https://dev.bukkit.org/projects/shopkeepers/issues/131

**Originally posted by RasCas (May 7, 2013):** 

2013-05-07 06:17:58 [WARNING] [Shopkeepers] Task #6471 for Shopkeepers v1.13.2 generated an exception
java.util.ConcurrentModificationException
Â  Â  at java.util.HashMap$HashIterator.remove(Unknown Source)
Â  Â  at com.nisovin.shopkeepers.ShopkeepersPlugin$4.run(ShopkeepersPlugin.java:583)
Â  Â  at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftTask.run(CraftTask.java:53)
Â  Â  at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
Â  Â  at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:513)
Â  Â  at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:226)
Â  Â  at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:477)
Â  Â  at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:410)
Â  Â  at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)Running Bukkit 1.52 r01

**Comment by blablubbabcDEV** [comment]
**Originally commented by RasCas (May 7, 2013):** 

It happens, when you name a shop(keeper) by clicking the anvil

            Edited May 7, 2013

**Comment by blablubbabcDEV** [comment]
**Originally closed by nisovin (Jul 5, 2013)**
