### ISSUE TITLE
ask #906451 for Shopkeepers v1.13.2 generated an exception

### ISSUE THREAD

**Issue by blablubbabcDEV** [Shopkeepers/Shopkeepers#145]
**Migrated from:** https://dev.bukkit.org/projects/shopkeepers/issues/136

**Originally posted by jeannen (May 9, 2013):** 

2013-05-09 14:26:34 [WARNING] [Shopkeepers] Task #906451 for Shopkeepers v1.13.2 generated an exception
java.util.ConcurrentModificationException
at java.util.HashMap$HashIterator.remove(HashMap.java:824)
at com.nisovin.shopkeepers.ShopkeepersPlugin$4.run(ShopkeepersPlugin.java:583)
at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftTask.run(CraftTask.java:53)
at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:513)
at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:226)
at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:477)
at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:410)
at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
I use the last Bukkit dev and the last version of shopkeepers

**Comment by blablubbabcDEV** [comment]
**Originally commented by jeannen (May 12, 2013):** 

i use Shopkeepers v1.13.2 and bukkit 2271 ...

**Comment by blablubbabcDEV** [comment]
**Originally closed by nisovin (Jul 5, 2013)**
