### ISSUE TITLE
add item to shop

### ISSUE THREAD

**Issue by blablubbabcDEV** [Shopkeepers/Shopkeepers#149]
**Migrated from:** https://dev.bukkit.org/projects/shopkeepers/issues/140

**Originally posted by henkoe (May 11, 2013):** 

What is the issue?Please provide any additional information below.When adding a item in a shop, it's creating the folowing error in the console:11.05 00:46:02 [Server] INFO at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
11.05 00:46:02 [Server] INFO at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:410)
11.05 00:46:02 [Server] INFO at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:477)
11.05 00:46:02 [Server] INFO at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:226)
11.05 00:46:02 [Server] INFO at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:513)
11.05 00:46:02 [Server] INFO at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
11.05 00:46:02 [Server] INFO at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftTask.run(CraftTask.java:53)
11.05 00:46:02 [Server] INFO at com.nisovin.shopkeepers.ShopkeepersPlugin$4.run(ShopkeepersPlugin.java:594)
11.05 00:46:02 [Server] INFO at java.util.HashMap$HashIterator.remove(HashMap.java:912)
11.05 00:46:02 [Server] INFO java.util.ConcurrentModificationException
11.05 00:46:02 [Server] WARNING Task #19839 for Shopkeepers v1.13.2 generated an exception

**Comment by blablubbabcDEV** [comment]
**Originally closed by nisovin (Jul 5, 2013)**
