### ISSUE TITLE
Task #3457 for Shopkeepers v1.13.2 generated an exception

### ISSUE THREAD

**Issue by blablubbabcDEV** [Shopkeepers/Shopkeepers#151]
**Migrated from:** https://dev.bukkit.org/projects/shopkeepers/issues/142

**Originally posted by br45entei (May 11, 2013):** 

What steps will reproduce the problem?
1. Type in /shopkeeper
2. Watch the console
3. Get an errorWhat is the expected output? What do you see instead?
I expected to see no errors, just a working plugin.What version of the product are you using?
Shopkeepers version: 1.13.2Do you have an error log of what happened?
Yes, it is not too long:
----------------------------------------------------------------------------------------------------------------------------------------------------------------
07:56:09 [INFO] Brian_Entei issued server command: "/shopkeeper".
07:56:21 [WARNING] [Shopkeepers] Task #3457 for Shopkeepers v1.13.2 generated an exception
java.util.ConcurrentModificationException
Â  Â  Â  Â  at java.util.HashMap$HashIterator.remove(Unknown Source)
Â  Â  Â  Â  at com.nisovin.shopkeepers.ShopkeepersPlugin$4.run(ShopkeepersPlugin.java:583)
Â  Â  Â  Â  at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftTask.run(CraftTask.java:58)
Â  Â  Â  Â  at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:344)
Â  Â  Â  Â  at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:509)
Â  Â  Â  Â  at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:224)
Â  Â  Â  Â  at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:472)
Â  Â  Â  Â  at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:404)
Â  Â  Â  Â  at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
----------------------------------------------------------------------------------------------------------------------------------------------------------------Please provide any additional information below.
I don't know that it matters, but I was on a world loaded with My Worlds.It may matter that I use a Spigot Server, but I doubt it because Spigot builds off of bukkit.

**Comment by blablubbabcDEV** [comment]
**Originally closed by nisovin (Jul 5, 2013)**
