### ISSUE TITLE
error on renaming a shopkeeper

### ISSUE THREAD

**Issue by blablubbabcDEV** [Shopkeepers/Shopkeepers#155]
**Migrated from:** https://dev.bukkit.org/projects/shopkeepers/issues/146

**Originally posted by blablubbabc (May 19, 2013):** 

Can't tell why this popped up.. it defenetly worked in thr past..18:14:25 [WARNING] [Shopkeepers] Task #77347 for Shopkeepers v1.13.2 generated an exception
java.util.ConcurrentModificationException
Â  Â  Â  Â  at java.util.HashMap$HashIterator.remove(HashMap.java:912)
Â  Â  Â  Â  at com.nisovin.shopkeepers.ShopkeepersPlugin$4.run(ShopkeepersPlugin.java:583)
Â  Â  Â  Â  at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftTask.run(CraftTask.java:58)
Â  Â  Â  Â  at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:344)
Â  Â  Â  Â  at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:509)
Â  Â  Â  Â  at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:227)
Â  Â  Â  Â  at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:472)
Â  Â  Â  Â  at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:404)
Â  Â  Â  Â  at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)

**Comment by blablubbabcDEV** [comment]
**Originally closed by nisovin (Jul 5, 2013)**
