### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by blablubbabcDEV** [Shopkeepers/Shopkeepers#157]
**Migrated from:** https://dev.bukkit.org/projects/shopkeepers/issues/148

**Originally posted by PhanaticD (May 23, 2013):** 

Happens occasionally in the server log, to sure how to reproduce09:35:50 [WARNING] [Shopkeepers] Task #17873 for Shopkeepers v1.13.2 generated an exception
java.util.ConcurrentModificationException
Â  Â  Â  Â  at java.util.HashMap$HashIterator.remove(HashMap.java:912)
Â  Â  Â  Â  at com.nisovin.shopkeepers.ShopkeepersPlugin$4.run(ShopkeepersPlugin.java:583)
Â  Â  Â  Â  at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftTask.run(CraftTask.java:67)
Â  Â  Â  Â  at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:344)
Â  Â  Â  Â  at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:509)
Â  Â  Â  Â  at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:227)
Â  Â  Â  Â  at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:472)
Â  Â  Â  Â  at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:404)
Â  Â  Â  Â  at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)

**Comment by blablubbabcDEV** [comment]
**Originally commented by Cueball61 (May 23, 2013):** 

For reference:
https://code.google.com/p/nisovin-minecraft-bukkit-plugins/source/browse/trunk/ShopKeepers/src/com/nisovin/shopkeepers/ShopkeepersPlugin.java#583
Seems like something on another thread (not necessarily L583) is accessing purchasers at the same time).

**Comment by blablubbabcDEV** [comment]
**Originally closed by nisovin (Jul 5, 2013)**
