### ISSUE TITLE
Execption Generated

### ISSUE THREAD

**Issue by blablubbabcDEV** [Shopkeepers/Shopkeepers#163]
**Migrated from:** https://dev.bukkit.org/projects/shopkeepers/issues/154

**Originally posted by UltrafaceGuy (Jun 7, 2013):** 

Got this error, just annoying doesn't hurt the server, fix it when you have time I guessKeep up the great work!2013-06-06 20:11:50 [WARNING] [Shopkeepers] Task #194605 for Shopkeepers v1.13.2 generated an exception
java.util.ConcurrentModificationException
Â  Â  at java.util.HashMap$HashIterator.remove(Unknown Source)
Â  Â  at com.nisovin.shopkeepers.ShopkeepersPlugin$4.run(ShopkeepersPlugin.java:583)
Â  Â  at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:58)
Â  Â  at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:344)
Â  Â  at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:516)
Â  Â  at net.minecraft.server.DedicatedServer.r(DedicatedServer.java:224)
Â  Â  at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:477)
Â  Â  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:409)
Â  Â  at net.minecraft.server.ThreadServerApplication.run(SourceFile:573)And have a nice day ;D

**Comment by blablubbabcDEV** [comment]
**Originally commented by nyghtwulf (Jun 15, 2013):** 

I'm getting these as well;

running CraftBukkit version git-Bukkit-1.5.2-R0.1-b2771jnks (MC: 1.5.2) (Implementing API version 1.5.2-R0.1)

with plugin version v1.13.3

Seems to occur shortly after making a new villager shopkeeper (admin style) and while doing config of the shop.

**Comment by blablubbabcDEV** [comment]
**Originally closed by nisovin (Jul 5, 2013)**
