### ISSUE TITLE
SEVERE error on server startup

### ISSUE THREAD

**Issue by blablubbabcDEV** [Shopkeepers/Shopkeepers#167]
**Migrated from:** https://dev.bukkit.org/projects/shopkeepers/issues/158

**Originally posted by Jo11yWombat (Jun 19, 2013):** 

Upon reloading my server lately I've been getting this in the console:2013-06-19 16:24:53 [INFO] [Shopkeepers] Enabling Shopkeepers v1.13.32013-06-19 16:24:53 [SEVERE] org.bukkit.configuration.InvalidConfigurationException: unacceptable character 'ï¿½' (0xFFFD) special characters are not allowedin &quot;&quot;, position 444552013-06-19 16:24:53 [SEVERE]Â Â  Â  at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55)2013-06-19 16:24:53 [SEVERE]Â Â  Â  at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:138)2013-06-19 16:24:53 [SEVERE]Â Â  Â  at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:105)2013-06-19 16:24:53 [SEVERE]Â Â  Â  at com.nisovin.shopkeepers.ShopkeepersPlugin.load(ShopkeepersPlugin.java:700)2013-06-19 16:24:53 [SEVERE]Â Â  Â  at com.nisovin.shopkeepers.ShopkeepersPlugin.onEnable(ShopkeepersPlugin.java:126)2013-06-19 16:24:53 [SEVERE]Â Â  Â  at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)2013-06-19 16:24:53 [SEVERE]Â Â  Â  at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:457)2013-06-19 16:24:53 [SEVERE]Â Â  Â  at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)2013-06-19 16:24:53 [SEVERE]Â Â  Â  at org.bukkit.craftbukkit.v1_5_R3.CraftServer.loadPlugin(CraftServer.java:282)2013-06-19 16:24:53 [SEVERE]Â Â  Â  at org.bukkit.craftbukkit.v1_5_R3.CraftServer.enablePlugins(CraftServer.java:264)2013-06-19 16:24:53 [SEVERE]Â Â  Â  at net.minecraft.server.v1_5_R3.MinecraftServer.j(MinecraftServer.java:304)2013-06-19 16:24:53 [SEVERE]Â Â  Â  at net.minecraft.server.v1_5_R3.MinecraftServer.e(MinecraftServer.java:283)2013-06-19 16:24:53 [SEVERE]Â Â  Â  at net.minecraft.server.v1_5_R3.MinecraftServer.a(MinecraftServer.java:243)2013-06-19 16:24:53 [SEVERE]Â Â  Â  at net.minecraft.server.v1_5_R3.DedicatedServer.init(DedicatedServer.java:151)2013-06-19 16:24:53 [SEVERE]Â Â  Â  at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:382)2013-06-19 16:24:53 [SEVERE]Â Â  Â  at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)2013-06-19 16:24:53 [SEVERE] Caused by: unacceptable character 'ï¿½' (0xFFFD) special characters are not allowedin &quot;&quot;, position 444552013-06-19 16:24:53 [SEVERE]Â Â  Â  at org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:70)2013-06-19 16:24:53 [SEVERE]Â Â  Â  at org.yaml.snakeyaml.reader.StreamReader.(StreamReader.java:50)2013-06-19 16:24:53 [SEVERE]Â Â  Â  at org.yaml.snakeyaml.Yaml.load(Yaml.java:399)2013-06-19 16:24:53 [SEVERE]Â Â  Â  at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53)2013-06-19 16:24:53 [SEVERE]Â Â  Â  ... 15 moreI'm using the latest version of Shopkeeper and the only just barely out of date version of bukkit (build 2771).The plugin still seems to load, and I can still spawn shopkeepers, I just don't like seeing severe warnings on start up...

**Comment by blablubbabcDEV** [comment]
**Originally commented by nisovin (Jun 25, 2013):** 

You have special characters in your save file. You should consider changing the encoding option in the config, and change the encoding of the file.

**Comment by blablubbabcDEV** [comment]
**Originally closed by nisovin (Jul 5, 2013)**
