### ISSUE TITLE
major bug all shopkeepers disappear

### ISSUE THREAD

**Issue by blablubbabcDEV** [Shopkeepers/Shopkeepers#170]
**Migrated from:** https://dev.bukkit.org/projects/shopkeepers/issues/161

**Originally posted by PhanaticD (Jun 28, 2013):** 

I start my server, get this error, and instantly hundred of shopkeepers are gone...
http://pastebin.com/3Av8ztTp

**Comment by blablubbabcDEV** [comment]
**Originally commented by amli2011 (Jul 4, 2013):** 

After update to craftbukkit 1.6.1 (#2805) and shopkeepers v1.14.1 (broken) i get the same error as PhanaticD.
I haven't changed anything in the config or save files. Did work on CB 1.5.2-R1.0 (0.2 0.1 etc) and the coresponding versions of shopkeeper. 
Other yml files for other plugins does load. 
Other plugins on my server (in case any of them is a part of the trouble - but did work together in 1.5.2):
BetterAlias
ChatManager
CoreProtect
dynmap
Essentials
Inception
Lockette
Modifyworld
Multiverse (core, inventories, netherportals and portals)
PermissionsEx
SkylandsPlus
uSkyBlock
Vault
WGCustomFlags
WGRegionEvents
WGTexturepackFlag
WorldGuard
In case you need more info, give me a PM :)
Thank you for a great plugin!

**Comment by blablubbabcDEV** [comment]
**Originally commented by nisovin (Jul 5, 2013):** 

Change your save.yml encoding to UTF-8, and set the file-encoding option in the config to "UTF-8" as well.

**Comment by blablubbabcDEV** [comment]
**Originally commented by amli2011 (Jul 5, 2013):** 

Thank you for your time.
The whole system is on UTF-8. Checked and confirmed that both save.yml and config-yml is in UTF-8.
Added line: 
file-encoding: "UTF-8" 
to config.yml and restarted.
Still no Shopkeepers. and same error during startup:
08:34:48 [INFO] [Shopkeepers] Enabling Shopkeepers v1.14.1
08:34:49 [SEVERE] org.bukkit.configuration.InvalidConfigurationException: unacceptable character 'ï¿½' (0xFFFD) special characters are not allowed
in "<string>", position 29517
08:34:49 [SEVERE] at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55)
08:34:49 [SEVERE] at com.nisovin.shopkeepers.ShopkeepersPlugin.load(ShopkeepersPlugin.java:702)
08:34:49 [SEVERE] at com.nisovin.shopkeepers.ShopkeepersPlugin.onEnable(ShopkeepersPlugin.java:125)
08:34:49 [SEVERE] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
08:34:49 [SEVERE] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:457)
08:34:49 [SEVERE] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
08:34:49 [SEVERE] at org.bukkit.craftbukkit.v1_6_R1.CraftServer.loadPlugin(CraftServer.java:282)
08:34:49 [SEVERE] at org.bukkit.craftbukkit.v1_6_R1.CraftServer.enablePlugins(CraftServer.java:264)
08:34:49 [SEVERE] at net.minecraft.server.v1_6_R1.MinecraftServer.l(MinecraftServer.java:313)
08:34:49 [SEVERE] at net.minecraft.server.v1_6_R1.MinecraftServer.f(MinecraftServer.java:290)
08:34:49 [SEVERE] at net.minecraft.server.v1_6_R1.MinecraftServer.a(MinecraftServer.java:250)
08:34:49 [SEVERE] at net.minecraft.server.v1_6_R1.DedicatedServer.init(DedicatedServer.java:151)
08:34:49 [SEVERE] at net.minecraft.server.v1_6_R1.MinecraftServer.run(MinecraftServer.java:391)
08:34:49 [SEVERE] at net.minecraft.server.v1_6_R1.ThreadServerApplication.run(SourceFile:582)
08:34:49 [SEVERE] Caused by: unacceptable character 'ï¿½' (0xFFFD) special characters are not allowed
in "<string>", position 29517
08:34:49 [SEVERE] at org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:70)
08:34:49 [SEVERE] at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:50)
08:34:49 [SEVERE] at org.yaml.snakeyaml.Yaml.load(Yaml.java:399)
08:34:49 [SEVERE] at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53)
08:34:49 [SEVERE] ... 13 more
Checked my java version:
java -version
java version "1.7.0_19"
OpenJDK Runtime Environment (fedora-2.3.9.3.fc18-x86_64)
OpenJDK 64-Bit Server VM (build 23.7-b01, mixed mode)
I am going to try to switch over to Oracle JRE in case that will help.

**Comment by blablubbabcDEV** [comment]
**Originally commented by amli2011 (Jul 5, 2013):** 

No luck vith Oracle JRE.

**Comment by blablubbabcDEV** [comment]
**Originally commented by amli2011 (Jul 5, 2013):** 

Found the error. One of my users created a shopkeeper. In the end of that shopkeepers name there was an character that was not UTF-8. But the problem is still there. How can a user corupt a config file?

**Comment by blablubbabcDEV** [comment]
**Originally commented by nisovin (Jul 25, 2013):** 

I've added an option to prevent unusual characters from shop names in 1.15.

**Comment by blablubbabcDEV** [comment]
**Originally closed by nisovin (Jul 25, 2013)**
