### ISSUE TITLE
NPE in console

### ISSUE THREAD

**Issue by blablubbabcDEV** [Shopkeepers/Shopkeepers#209]
**Migrated from:** https://dev.bukkit.org/projects/shopkeepers/issues/202

**Originally posted by PhanaticD (Dec 11, 2013):** 

see this in my console, I am assuming on auto-save
[00:25:41 WARN]: [Shopkeepers] Task #34 for Shopkeepers v1.16-beta generated an exception
java.lang.NullPointerException
        at com.nisovin.shopkeepers.volatilecode.VolatileCode_1_7_R1.saveItemAttributesToString(VolatileCode_1_7_R1.java:156) ~[?:?]
        at com.nisovin.shopkeepers.shoptypes.TradingPlayerShopkeeper.save(TradingPlayerShopkeeper.java:75) ~[?:?]
        at com.nisovin.shopkeepers.ShopkeepersPlugin.saveReal(ShopkeepersPlugin.java:901) ~[?:?]
        at com.nisovin.shopkeepers.ShopkeepersPlugin.access$2(ShopkeepersPlugin.java:895) ~[?:?]
        at com.nisovin.shopkeepers.ShopkeepersPlugin$3.run(ShopkeepersPlugin.java:228) ~[?:?]
        at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftTask.run(CraftTask.java:67) ~[craftbukkit.jar:git-Spigot-1178]
        at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345) [craftbukkit.jar:git-Spigot-1178]
        at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:573) [craftbukkit.jar:git-Spigot-1178]
        at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:259) [craftbukkit.jar:git-Spigot-1178]
        at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:530) [craftbukkit.jar:git-Spigot-1178]
        at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:442) [craftbukkit.jar:git-Spigot-1178]
        at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [craftbukkit.jar:git-Spigot-1178]

**Comment by blablubbabcDEV** [comment]
**Originally commented by blablubbabc (Dec 11, 2013):** 

Please try again with the 1.6 -beta2 file, as soon as it has been approved by a staff and is available as download.

**Comment by blablubbabcDEV** [comment]
**Originally closed by nisovin (Dec 14, 2013)**
