### ISSUE TITLE
Console error on Shopkeeper Interaction

### ISSUE THREAD

**Issue by blablubbabcDEV** [Shopkeepers/Shopkeepers#244]
**Migrated from:** https://dev.bukkit.org/projects/shopkeepers/issues/239

**Originally posted by StarvingMiner (Jul 9, 2014):** 

Every time a player interacts with a shopkeeper, the console gets spammed with an error. It doesn't seem to be affecting anything, as players can still buy and sell goods without error. I am seeing no problem, only that I do not want my console getting spammed. I am using the latest version of spigot 1.7.9 with the latest version of Shopkeepers. Here is the console error:[15:50:44 ERROR]: [AttributeHider] Unhandled exception occured in onPacketSendin
g(PacketEvent) for AttributeHider
java.lang.NullPointerException
Â  Â  Â  Â  at org.apache.logging.log4j.core.config.AppenderControl.callAppender(App
enderControl.java:101) ~[spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(Logge
rConfig.java:425) ~[spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.ja
va:406) ~[spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.ja
va:367) ~[spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at org.apache.logging.log4j.core.Logger.log(Logger.java:110) ~[spigot.ja
r:git-Spigot-1543]
Â  Â  Â  Â  at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java
:609) ~[spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at org.bukkit.craftbukkit.v1_7_R3.util.ForwardLogHandler.publish(Forward
LogHandler.java:33) ~[spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at java.util.logging.Logger.log(Unknown Source) ~[?:1.7.0_51]
Â  Â  Â  Â  at java.util.logging.Logger.doLog(Unknown Source) ~[?:1.7.0_51]
Â  Â  Â  Â  at java.util.logging.Logger.log(Unknown Source) ~[?:1.7.0_51]
Â  Â  Â  Â  at me.mncat77.plugins.attributehider.AttributeHider$1.onPacketSending(At
tributeHider.java:113) ~[AttributeHider-v1.2.3.jar:?]
Â  Â  Â  Â  at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendin
gListener(SortedPacketListenerList.java:195) [ProtocolLib-3.4.0.jar:?]
Â  Â  Â  Â  at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacket
Sending(SortedPacketListenerList.java:149) [ProtocolLib-3.4.0.jar:?]
Â  Â  Â  Â  at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(Pack
etFilterManager.java:612) [ProtocolLib-3.4.0.jar:?]
Â  Â  Â  Â  at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSendi
ng(PacketFilterManager.java:588) [ProtocolLib-3.4.0.jar:?]
Â  Â  Â  Â  at com.comphenix.protocol.injector.netty.NettyProtocolInjector.packetQue
ued(NettyProtocolInjector.java:281) [ProtocolLib-3.4.0.jar:?]
Â  Â  Â  Â  at com.comphenix.protocol.injector.netty.NettyProtocolInjector.onPacketS
ending(NettyProtocolInjector.java:249) [ProtocolLib-3.4.0.jar:?]
Â  Â  Â  Â  at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(
ChannelInjector.java:319) [ProtocolLib-3.4.0.jar:?]
Â  Â  Â  Â  at com.comphenix.protocol.injector.netty.ChannelInjector.access$300(Chan
nelInjector.java:59) [ProtocolLib-3.4.0.jar:?]
Â  Â  Â  Â  at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleSchedul
ed(ChannelInjector.java:295) [ProtocolLib-3.4.0.jar:?]
Â  Â  Â  Â  at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageSche
duled(ChannelInjector.java:263) [ProtocolLib-3.4.0.jar:?]
Â  Â  Â  Â  at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnab
le(ChannelProxy.java:100) [ProtocolLib-3.4.0.jar:?]
Â  Â  Â  Â  at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoo
pProxy.java:76) [ProtocolLib-3.4.0.jar:?]
Â  Â  Â  Â  at net.minecraft.server.v1_7_R3.NetworkManager.b(NetworkManager.java:149
) [spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at net.minecraft.server.v1_7_R3.NetworkManager.handle(NetworkManager.jav
a:127) [spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at net.minecraft.server.v1_7_R3.PlayerConnection.sendPacket(PlayerConnec
tion.java:768) [spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at net.minecraft.server.v1_7_R3.EntityPlayer.openTrade(EntityPlayer.java
:776) [spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at net.minecraft.server.v1_7_R3.EntityVillager.a(SourceFile:147) [spigot
.jar:git-Spigot-1543]
Â  Â  Â  Â  at com.nisovin.shopkeepers.compat.v1_7_R3.NMSHandler.openTradeWindow(NMS
Handler.java:47) [Shopkeepers.jar:?]
Â  Â  Â  Â  at com.nisovin.shopkeepers.compat.v1_7_R3.NMSHandler.openTradeWindow(NMS
Handler.java:58) [Shopkeepers.jar:?]
Â  Â  Â  Â  at com.nisovin.shopkeepers.ShopkeepersPlugin.openTradeWindow(Shopkeepers
Plugin.java:834) [Shopkeepers.jar:?]
Â  Â  Â  Â  at com.nisovin.shopkeepers.ShopkeepersPlugin.handleShopkeeperInteraction
(ShopkeepersPlugin.java:726) [Shopkeepers.jar:?]
Â  Â  Â  Â  at com.nisovin.shopkeepers.VillagerListener.onEntityInteract(VillagerLis
tener.java:31) [Shopkeepers.jar:?]
Â  Â  Â  Â  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0
_51]
Â  Â  Â  Â  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0
_51]
Â  Â  Â  Â  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.7.0_51]
Â  Â  Â  Â  at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_51]
Â  Â  Â  Â  at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:296) [spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) [spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:502) [spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:487) [spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at net.minecraft.server.v1_7_R3.PlayerConnection.a(PlayerConnection.java
:1141) [spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at net.minecraft.server.v1_7_R3.PacketPlayInUseEntity.a(SourceFile:55) [
spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at net.minecraft.server.v1_7_R3.PacketPlayInUseEntity.handle(SourceFile:
10) [spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at net.minecraft.server.v1_7_R3.NetworkManager.a(NetworkManager.java:184
) [spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at net.minecraft.server.v1_7_R3.ServerConnection.c(ServerConnection.java
:81) [spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:7
31) [spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:2
84) [spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:5
84) [spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java
:490) [spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:6
28) [spigot.jar:git-Spigot-1543]
[15:50:44 ERROR]: Parameters:
Â  net.minecraft.server.v1_7_R3.PacketPlayOutCustomPayload[at]7fb9c2fd[
Â  Â  tag=MC|TrList
Â  Â  data={0,0,0,2,4,1,31,16,0,0,0,46,31,-117,8,0,0,0,0,0,0,0,-29,98,96,-32,100,1
6,114,44,41,41,-54,76,42,45,73,-11,-51,79,-55,76,-53,76,45,42,102,0,3,0,108,102,
-109,104,30,0,0,0,1,-124,4,0,0,0,46,31,-117,8,0,0,0,0,0,0,0,-29,98,96,-32,100,16
,114,44,41,41,-54,76,42,45,73,-11,-51,79,-55,76,-53,76,45,42,102,0,3,0,108,102,-
109,104,30,0,0,0,0,0,1,119,16,0,0,0,46,31,-117,8,0,0,0,0,0,0,0,-29,98,96,-32,100
,16,114,44,41,41,-54,76,42,45,73,-11,-51,79,-55,76,-53,76,45,42,102,0,3,0,108,10
2,-109,104,30,0,0,0,1,-124,6,0,0,0,46,31,-117,8,0,0,0,0,0,0,0,-29,98,96,-32,100,
16,114,44,41,41,-54,76,42,45,73,-11,-51,79,-55,76,-53,76,45,42,102,0,3,0,108,102
,-109,104,30,0,0,0,0,0,1,96,16,0,0,0,46,31,-117,8,0,0,0,0,0,0,0,-29,98,96,-32,10
0,16,114,44,41,41,-54,76,42,45,73,-11,-51,79,-55,76,-53,76,45,42,102,0,3,0,108,1
02,-109,104,30,0,0,0,1,-124,4,0,0,0,46,31,-117,8,0,0,0,0,0,0,0,-29,98,96,-32,100
,16,114,44,41,41,-54,76,42,45,73,-11,-51,79,-55,76,-53,76,45,42,102,0,3,0,108,10
2,-109,104,30,0,0,0,0,0,1,111,16,0,0,0,46,31,-117,8,0,0,0,0,0,0,0,-29,98,96,-32,
100,16,114,44,41,41,-54,76,42,45,73,-11,-51,79,-55,76,-53,76,45,42,102,0,3,0,108
,102,-109,104,30,0,0,0,1,-124,6,0,0,0,46,31,-117,8,0,0,0,0,0,0,0,-29,98,96,-32,1
00,16,114,44,41,41,-54,76,42,45,73,-11,-51,79,-55,76,-53,76,45,42,102,0,3,0,108,
102,-109,104,30,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0}
Â  Â  timestamp=1404939044386
Â  ][15:50:49 ERROR]: [AttributeHider] Unhandled exception occured in onPacketSendin
g(PacketEvent) for AttributeHider
java.lang.NullPointerException
Â  Â  Â  Â  at org.apache.logging.log4j.core.config.AppenderControl.callAppender(App
enderControl.java:101) ~[spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(Logge
rConfig.java:425) ~[spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.ja
va:406) ~[spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.ja
va:367) ~[spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at org.apache.logging.log4j.core.Logger.log(Logger.java:110) ~[spigot.ja
r:git-Spigot-1543]
Â  Â  Â  Â  at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java
:609) ~[spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at org.bukkit.craftbukkit.v1_7_R3.util.ForwardLogHandler.publish(Forward
LogHandler.java:33) ~[spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at java.util.logging.Logger.log(Unknown Source) ~[?:1.7.0_51]
Â  Â  Â  Â  at java.util.logging.Logger.doLog(Unknown Source) ~[?:1.7.0_51]
Â  Â  Â  Â  at java.util.logging.Logger.log(Unknown Source) ~[?:1.7.0_51]
Â  Â  Â  Â  at me.mncat77.plugins.attributehider.AttributeHider$1.onPacketSending(At
tributeHider.java:113) ~[AttributeHider-v1.2.3.jar:?]
Â  Â  Â  Â  at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendin
gListener(SortedPacketListenerList.java:195) [ProtocolLib-3.4.0.jar:?]
Â  Â  Â  Â  at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacket
Sending(SortedPacketListenerList.java:149) [ProtocolLib-3.4.0.jar:?]
Â  Â  Â  Â  at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(Pack
etFilterManager.java:612) [ProtocolLib-3.4.0.jar:?]
Â  Â  Â  Â  at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSendi
ng(PacketFilterManager.java:588) [ProtocolLib-3.4.0.jar:?]
Â  Â  Â  Â  at com.comphenix.protocol.injector.netty.NettyProtocolInjector.packetQue
ued(NettyProtocolInjector.java:281) [ProtocolLib-3.4.0.jar:?]
Â  Â  Â  Â  at com.comphenix.protocol.injector.netty.NettyProtocolInjector.onPacketS
ending(NettyProtocolInjector.java:249) [ProtocolLib-3.4.0.jar:?]
Â  Â  Â  Â  at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(
ChannelInjector.java:319) [ProtocolLib-3.4.0.jar:?]
Â  Â  Â  Â  at com.comphenix.protocol.injector.netty.ChannelInjector.access$300(Chan
nelInjector.java:59) [ProtocolLib-3.4.0.jar:?]
Â  Â  Â  Â  at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleSchedul
ed(ChannelInjector.java:295) [ProtocolLib-3.4.0.jar:?]
Â  Â  Â  Â  at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageSche
duled(ChannelInjector.java:263) [ProtocolLib-3.4.0.jar:?]
Â  Â  Â  Â  at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnab
le(ChannelProxy.java:100) [ProtocolLib-3.4.0.jar:?]
Â  Â  Â  Â  at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoo
pProxy.java:76) [ProtocolLib-3.4.0.jar:?]
Â  Â  Â  Â  at net.minecraft.server.v1_7_R3.NetworkManager.b(NetworkManager.java:149
) [spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at net.minecraft.server.v1_7_R3.NetworkManager.handle(NetworkManager.jav
a:127) [spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at net.minecraft.server.v1_7_R3.PlayerConnection.sendPacket(PlayerConnec
tion.java:768) [spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at net.minecraft.server.v1_7_R3.EntityPlayer.openTrade(EntityPlayer.java
:776) [spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at net.minecraft.server.v1_7_R3.EntityVillager.a(SourceFile:147) [spigot
.jar:git-Spigot-1543]
Â  Â  Â  Â  at com.nisovin.shopkeepers.compat.v1_7_R3.NMSHandler.openTradeWindow(NMS
Handler.java:47) [Shopkeepers.jar:?]
Â  Â  Â  Â  at com.nisovin.shopkeepers.compat.v1_7_R3.NMSHandler.openTradeWindow(NMS
Handler.java:58) [Shopkeepers.jar:?]
Â  Â  Â  Â  at com.nisovin.shopkeepers.ShopkeepersPlugin.openTradeWindow(Shopkeepers
Plugin.java:834) [Shopkeepers.jar:?]
Â  Â  Â  Â  at com.nisovin.shopkeepers.ShopkeepersPlugin.handleShopkeeperInteraction
(ShopkeepersPlugin.java:726) [Shopkeepers.jar:?]
Â  Â  Â  Â  at com.nisovin.shopkeepers.VillagerListener.onEntityInteract(VillagerLis
tener.java:31) [Shopkeepers.jar:?]
Â  Â  Â  Â  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0
_51]
Â  Â  Â  Â  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0
_51]
Â  Â  Â  Â  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.7.0_51]
Â  Â  Â  Â  at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_51]
Â  Â  Â  Â  at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:296) [spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) [spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:502) [spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:487) [spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at net.minecraft.server.v1_7_R3.PlayerConnection.a(PlayerConnection.java
:1141) [spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at net.minecraft.server.v1_7_R3.PacketPlayInUseEntity.a(SourceFile:55) [
spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at net.minecraft.server.v1_7_R3.PacketPlayInUseEntity.handle(SourceFile:
10) [spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at net.minecraft.server.v1_7_R3.NetworkManager.a(NetworkManager.java:184
) [spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at net.minecraft.server.v1_7_R3.ServerConnection.c(ServerConnection.java
:81) [spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:7
31) [spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:2
84) [spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:5
84) [spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java
:490) [spigot.jar:git-Spigot-1543]
Â  Â  Â  Â  at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:6
28) [spigot.jar:git-Spigot-1543]
[15:50:49 ERROR]: Parameters:
Â  net.minecraft.server.v1_7_R3.PacketPlayOutCustomPayload[at]4627a3d3[
Â  Â  tag=MC|TrList
Â  Â  data={0,0,0,3,6,1,7,16,0,0,0,46,31,-117,8,0,0,0,0,0,0,0,-29,98,96,-32,100,16
,114,44,41,41,-54,76,42,45,73,-11,-51,79,-55,76,-53,76,45,42,102,0,3,0,108,102,-
109,104,30,0,0,0,1,-124,4,0,0,0,46,31,-117,8,0,0,0,0,0,0,0,-29,98,96,-32,100,16,
114,44,41,41,-54,76,42,45,73,-11,-51,79,-55,76,-53,76,45,42,102,0,3,0,108,102,-1
09,104,30,0,0,0,0,0,1,75,16,0,0,0,46,31,-117,8,0,0,0,0,0,0,0,-29,98,96,-32,100,1
6,114,44,41,41,-54,76,42,45,73,-11,-51,79,-55,76,-53,76,45,42,102,0,3,0,108,102,
-109,104,30,0,0,0,1,-124,4,0,0,0,46,31,-117,8,0,0,0,0,0,0,0,-29,98,96,-32,100,16
,114,44,41,41,-54,76,42,45,73,-11,-51,79,-55,76,-53,76,45,42,102,0,3,0,108,102,-
109,104,30,0,0,0,0,0,1,95,16,0,4,0,46,31,-117,8,0,0,0,0,0,0,0,-29,98,96,-32,100,
16,114,44,41,41,-54,76,42,45,73,-11,-51,79,-55,76,-53,76,45,42,102,0,3,0,108,102
,-109,104,30,0,0,0,1,-124,4,0,0,0,46,31,-117,8,0,0,0,0,0,0,0,-29,98,96,-32,100,1
6,114,44,41,41,-54,76,42,45,73,-11,-51,79,-55,76,-53,76,45,42,102,0,3,0,108,102,
-109,104,30,0,0,0,0,0,0,15,8,0,0,0,46,31,-117,8,0,0,0,0,0,0,0,-29,98,96,-32,100,
16,114,44,41,41,-54,76,42,45,73,-11,-51,79,-55,76,-53,76,45,42,102,0,3,0,108,102
,-109,104,30,0,0,0,1,-124,6,0,0,0,46,31,-117,8,0,0,0,0,0,0,0,-29,98,96,-32,100,1
6,114,44,41,41,-54,76,42,45,73,-11,-51,79,-55,76,-53,76,45,42,102,0,3,0,108,102,
-109,104,30,0,0,0,0,0,0,14,8,0,0,0,46,31,-117,8,0,0,0,0,0,0,0,-29,98,96,-32,100,
16,114,44,41,41,-54,76,42,45,73,-11,-51,79,-55,76,-53,76,45,42,102,0,3,0,108,102
,-109,104,30,0,0,0,1,-124,8,0,0,0,46,31,-117,8,0,0,0,0,0,0,0,-29,98,96,-32,100,1
6,114,44,41,41,-54,76,42,45,73,-11,-51,79,-55,76,-53,76,45,42,102,0,3,0,108,102,
-109,104,30,0,0,0,0,0,1,8,4,0,0,0,46,31,-117,8,0,0,0,0,0,0,0,-29,98,96,-32,100,1
6,114,44,41,41,-54,76,42,45,73,-11,-51,79,-55,76,-53,76,45,42,102,0,3,0,108,102,
-109,104,30,0,0,0,1,-124,16,0,0,0,46,31,-117,8,0,0,0,0,0,0,0,-29,98,96,-32,100,1
6,114,44,41,41,-54,76,42,45,73,-11,-51,79,-55,76,-53,76,45,42,102,0,3,0,108,102,
-109,104,30,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}
Â  Â  timestamp=1404939049453I am using spigot and have protocollib installed

**Comment by blablubbabcDEV** [comment]
**Originally commented by blablubbabc (Jul 10, 2014):** 

From looking at the stacktrace it seems like an issue with AttributeHider, triggered and possibly implicitly caused by shopkeepers. But the author of AttributeHider might be able to tell you more on that.

**Comment by blablubbabcDEV** [comment]
**Originally commented by StarvingMiner (Jul 10, 2014):** 

Thanks!

**Comment by blablubbabcDEV** [comment]
**Originally closed by blablubbabc (Jul 10, 2014)**
