### ISSUE TITLE
Check argument

### ISSUE THREAD

**Issue by blablubbabcDEV** [Shopkeepers/Shopkeepers#28]
**Migrated from:** https://dev.bukkit.org/projects/shopkeepers/issues/18

**Originally posted by THDigi (Aug 20, 2012):** 

If using /shopkeeper with an argument that is not 1-5 or the profession names it will panic:
<<code text>>
07:06:15 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'shopkeeper' in plugin Shopkeepers v1.4
Â  Â  Â  Â  at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)
Â  Â  Â  Â  at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
Â  Â  Â  Â  at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:492)
Â  Â  Â  Â  at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:878)
Â  Â  Â  Â  at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:825)
Â  Â  Â  Â  at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:807)
Â  Â  Â  Â  at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:44)
Â  Â  Â  Â  at net.minecraft.server.NetworkManager.b(NetworkManager.java:276)
Â  Â  Â  Â  at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:109)
Â  Â  Â  Â  at net.minecraft.server.ServerConnection.b(SourceFile:35)
Â  Â  Â  Â  at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
Â  Â  Â  Â  at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:581)
Â  Â  Â  Â  at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:212)
Â  Â  Â  Â  at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:474)
Â  Â  Â  Â  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:406)
Â  Â  Â  Â  at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.entity.Villager.Profession.REMOVE
Â  Â  Â  Â  at java.lang.Enum.valueOf(Unknown Source)
Â  Â  Â  Â  at org.bukkit.entity.Villager$Profession.valueOf(Villager.java:25)
Â  Â  Â  Â  at com.nisovin.shopkeepers.ShopkeepersPlugin.onCommand(ShopkeepersPlugin.java:178)
Â  Â  Â  Â  at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
Â  Â  Â  Â  ... 15 more
<</code>>This came up when I used "/shopkeeper remove" xD

**Comment by blablubbabcDEV** [comment]
**Originally commented by nisovin (Aug 21, 2012):** 

I'm just removing the optional argument in 1.5. Now that I've added the profession switch button in the editor it isn't really necessary.

**Comment by blablubbabcDEV** [comment]
**Originally closed by nisovin (Aug 21, 2012)**
