### ISSUE TITLE
Plugin Bugs with heads

### ISSUE THREAD

**Issue by blablubbabcDEV** [Shopkeepers/Shopkeepers#334]
**Migrated from:** https://dev.bukkit.org/projects/shopkeepers/issues/333

**Originally posted by RowyOor (Jul 12, 2015):** 

What steps will reproduce the problem?
1. inserting a customized player head into a shop (we wanted to make a head shop)
2. make /shopkeeper reloadWhat is the expected output? What do you see instead?
save.yml on ftp is empty and all shops disappear.
I already tried switching file-encodingÂ  from "UTF-8" to empty "" encode with no luckWhat version of the product are you using?
1. v1.61 on spigot 1.8.3Do you have an error log of what happened?12.07 12:13:39 [Server] INFO at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:320) ~[spigot-1.8.3.jar:git-Spigot-1d14d5f-7722428] 12.07 12:13:39 [Server] INFO at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:157) ~[spigot-1.8.3.jar:git-Spigot-1d14d5f-7722428] 12.07 12:13:39 [Server] INFO at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95) ~[spigot-1.8.3.jar:git-Spigot-1d14d5f-7722428] 12.07 12:13:39 [Server] INFO at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSerializable.representData(YamlRepresenter.java:33) ~[spigot-1.8.3.jar:git-Spigot-1d14d5f-7722428] 12.07 12:13:39 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.inventory.CraftMetaItem.serialize(CraftMetaItem.java:851) ~[spigot-1.8.3.jar:git-Spigot-1d14d5f-7722428] 12.07 12:13:39 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.inventory.CraftMetaSkull.serialize(CraftMetaSkull.java:150) ~[spigot-1.8.3.jar:git-Spigot-1d14d5f-7722428] 12.07 12:13:39 [Server] INFO at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:206) ~[spigot-1.8.3.jar:git-Spigot-1d14d5f-7722428] 12.07 12:13:39 [Server] INFO at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:135) ~[spigot-1.8.3.jar:git-Spigot-1d14d5f-7722428] 12.07 12:13:39 [Server] INFO at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:33) ~[spigot-1.8.3.jar:git-Spigot-1d14d5f-7722428] 12.07 12:13:39 [Server] INFO Caused by: java.lang.NullPointerException: null value in entry: skull-owner=null 12.07 12:13:39 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0] 12.07 12:13:39 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot-1.8.3.jar:git-Spigot-1d14d5f-7722428] 12.07 12:13:39 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot-1.8.3.jar:git-Spigot-1d14d5f-7722428] 12.07 12:13:39 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot-1.8.3.jar:git-Spigot-1d14d5f-7722428] 12.07 12:13:39 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot-1.8.3.jar:git-Spigot-1d14d5f-7722428] 12.07 12:13:39 [Server] INFO at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot-1.8.3.jar:git-Spigot-1d14d5f-7722428] 12.07 12:13:39 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0] 12.07 12:13:39 [Server] INFO at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source) [?:1.7.0] 12.07 12:13:39 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0] 12.07 12:13:39 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.3.jar:git-Spigot-1d14d5f-7722428] 12.07 12:13:39 [Server] INFO at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.3.jar:git-Spigot-1d14d5f-7722428] 12.07 12:13:39 [Server] INFO at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.3.jar:git-Spigot-1d14d5f-7722428] 12.07 12:13:39 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:974) [spigot-1.8.3.jar:git-Spigot-1d14d5f-7722428] 12.07 12:13:39 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1139) [spigot-1.8.3.jar:git-Spigot-1d14d5f-7722428] 12.07 12:13:39 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot-1.8.3.jar:git-Spigot-1d14d5f-7722428] 12.07 12:13:39 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.3.jar:git-Spigot-1d14d5f-7722428] 12.07 12:13:39 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.3.jar:git-Spigot-1d14d5f-7722428] 12.07 12:13:39 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'shopkeeper' in plugin Shopkeepers v1.61 12.07 12:13:39 [Server] ERROR nullPlease provide any additional information below.Any suggestion?
Thanks

**Comment by blablubbabcDEV** [comment]
**Originally commented by blablubbabc (Jul 12, 2015):** 

Duplicate of this ticket: http://dev.bukkit.org/bukkit-plugins/shopkeepers/tickets/298-shopkeeper-save-file-corrution/
This is something the spigot team has to fix in their item serialization which Shopkeepers uses.
Edit: In the next version I will try to detect this error and then disable the plugin without triggering another save. This hopefully prevents that all the shopkeeper data gets lost if there is an error during loading.

            Edited Jul 12, 2015

**Comment by blablubbabcDEV** [comment]
**Originally closed by blablubbabc (Jul 12, 2015)**
