### ISSUE TITLE
Shopkeeper Problems with Playerheads

### ISSUE THREAD

**Issue by blablubbabcDEV** [Shopkeepers/Shopkeepers#345]
**Migrated from:** https://dev.bukkit.org/projects/shopkeepers/issues/344

**Originally posted by Telbaru (Oct 4, 2015):** 

Everytime you sell Player heads with the Villagers and the player from this head change his name, the plugin deletes the complete save.yml because the plugin didn't find the playerheads name.Running System: - CraftBukkit version git-Spigot-fdc1440-53fac9f (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  - Shopkeepers v1.63Error:
[17:32:11] [Craft Scheduler Thread - 299/WARN]: Exception in thread "Craft Scheduler Thread - 299"
[17:32:11] [Craft Scheduler Thread - 299/WARN]: org.apache.commons.lang.UnhandledException: Plugin Shopkeepers v1.63 generated an exception while executing task 81576
Â  Â  at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
Â  Â  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
Â  Â  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
Â  Â  at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: null value in entry: skull-owner=null
Â  Â  at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:33)
Â  Â  at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:135)
Â  Â  at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:206)
Â  Â  at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftMetaSkull.serialize(CraftMetaSkull.java:173)
Â  Â  at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftMetaItem.serialize(CraftMetaItem.java:850)
Â  Â  at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSerializable.representData(YamlRepresenter.java:33)
Â  Â  at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94)
Â  Â  at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:156)
Â  Â  at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304)
Â  Â  at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSerializable.representData(YamlRepresenter.java:35)
Â  Â  at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94)
Â  Â  at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:156)
Â  Â  at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304)
Â  Â  at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSection.representData(YamlRepresenter.java:23)
Â  Â  at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94)
Â  Â  at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:156)
Â  Â  at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304)
Â  Â  at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSection.representData(YamlRepresenter.java:23)
Â  Â  at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94)
Â  Â  at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:156)
Â  Â  at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304)
Â  Â  at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSection.representData(YamlRepresenter.java:23)
Â  Â  at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94)
Â  Â  at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:156)
Â  Â  at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304)
Â  Â  at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94)
Â  Â  at org.yaml.snakeyaml.representer.BaseRepresenter.represent(BaseRepresenter.java:64)
Â  Â  at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:242)
Â  Â  at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:206)
Â  Â  at org.yaml.snakeyaml.Yaml.dump(Yaml.java:181)
Â  Â  at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:40)
Â  Â  at com.nisovin.shopkeepers.ShopkeepersPlugin.saveDataToFile(ShopkeepersPlugin.java:1390)
Â  Â  at com.nisovin.shopkeepers.ShopkeepersPlugin.access$1200(ShopkeepersPlugin.java:62)
Â  Â  at com.nisovin.shopkeepers.ShopkeepersPlugin$11.run(ShopkeepersPlugin.java:1300)
Â  Â  at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
Â  Â  at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
Â  Â  ... 3 more

**Comment by blablubbabcDEV** [comment]
**Originally commented by blablubbabc (Oct 4, 2015):** 

Duplicate of this closed ticket.
This is something the spigot team has to fix. I created a spigot ticket for it here.

**Comment by blablubbabcDEV** [comment]
**Originally closed by blablubbabc (Oct 4, 2015)**
