### ISSUE TITLE
Error Could not pass event spigot 1.9

### ISSUE THREAD

**Issue by blablubbabcDEV** [Shopkeepers/Shopkeepers#369]
**Migrated from:** https://dev.bukkit.org/projects/shopkeepers/issues/368

**Originally posted by trianl2 (Mar 12, 2016):** 

[23:10:20 ERROR]: Could not pass event PlayerInteractEntityEvent to Shopkeepers v1.70
org.bukkit.event.EventException
Â  Â  Â  Â  at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
Â  Â  Â  Â  at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
Â  Â  Â  Â  at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
Â  Â  Â  Â  at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
Â  Â  Â  Â  at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1484) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
Â  Â  Â  Â  at net.minecraft.server.v1_9_R1.PacketPlayInUseEntity.a(SourceFile:68) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
Â  Â  Â  Â  at net.minecraft.server.v1_9_R1.PacketPlayInUseEntity.a(SourceFile:12) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
Â  Â  Â  Â  at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
Â  Â  Â  Â  at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_80]
Â  Â  Â  Â  at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_80]
Â  Â  Â  Â  at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
Â  Â  Â  Â  at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
Â  Â  Â  Â  at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
Â  Â  Â  Â  at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
Â  Â  Â  Â  at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
Â  Â  Â  Â  at java.lang.Thread.run(Unknown Source) [?:1.7.0_80]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.player.PlayerInteractEntityEvent.getHand()Lorg/bukkit/inventory/EquipmentSlot;
Â  Â  Â  Â  at com.nisovin.shopkeepers.compat.v1_9_R1.NMSHandler.isMainHandInteraction(NMSHandler.java:330) ~[?:?]
Â  Â  Â  Â  at com.nisovin.shopkeepers.LivingEntityShopListener.onEntityInteract(LivingEntityShopListener.java:56) ~[?:?]
Â  Â  Â  Â  at sun.reflect.GeneratedMethodAccessor77.invoke(Unknown Source) ~[?:?]
Â  Â  Â  Â  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_80]
Â  Â  Â  Â  at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_80]
Â  Â  Â  Â  at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]
Â  Â  Â  Â  ... 15 more

**Comment by blablubbabcDEV** [comment]
**Originally commented by blablubbabc (Mar 14, 2016):** 

Update your spigot server. Shopkeepers requires a later version of Spigot 1.9.

**Comment by blablubbabcDEV** [comment]
**Originally closed by blablubbabc (Mar 14, 2016)**
