### ISSUE TITLE
when I right click while sneaking the shopkeeper nothing happens

### ISSUE THREAD

**Issue by blablubbabcDEV** [Shopkeepers/Shopkeepers#378]
**Migrated from:** https://dev.bukkit.org/projects/shopkeepers/issues/377

**Originally posted by QUIQUELHAPPY (Mar 28, 2016):** 

when I right click while sneaking the shopkeeper nothing happens

**Comment by blablubbabcDEV** [comment]
**Originally commented by QUIQUELHAPPY (Mar 28, 2016):** 

Could not pass event PlayerInteractEntityEvent to Shopkeepers v1.70
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-604e046-69e196f]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-604e046-69e196f]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-604e046-69e196f]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-604e046-69e196f]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1484) [spigot.jar:git-Spigot-604e046-69e196f]
        at net.minecraft.server.v1_9_R1.PacketPlayInUseEntity.a(SourceFile:68) [spigot.jar:git-Spigot-604e046-69e196f]
        at net.minecraft.server.v1_9_R1.PacketPlayInUseEntity.a(SourceFile:12) [spigot.jar:git-Spigot-604e046-69e196f]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-604e046-69e196f]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-604e046-69e196f]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:716) [spigot.jar:git-Spigot-604e046-69e196f]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-604e046-69e196f]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655) [spigot.jar:git-Spigot-604e046-69e196f]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-604e046-69e196f]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.player.PlayerInteractEntityEvent.getHand()Lorg/bukkit/inventory/EquipmentSlot;
        at com.nisovin.shopkeepers.compat.v1_9_R1.NMSHandler.isMainHandInteraction(NMSHandler.java:330) ~[?:?]
        at com.nisovin.shopkeepers.LivingEntityShopListener.onEntityInteract(LivingEntityShopListener.java:56) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor1051.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-604e046-69e196f]
        ... 15 more

**Comment by blablubbabcDEV** [comment]
**Originally commented by blablubbabc (Mar 28, 2016):** 

Update your spigot server.

**Comment by blablubbabcDEV** [comment]
**Originally closed by blablubbabc (Mar 28, 2016)**
