### ISSUE TITLE
Cannot edit shopkeepers

### ISSUE THREAD

**Issue by blablubbabcDEV** [Shopkeepers/Shopkeepers#381]
**Migrated from:** https://dev.bukkit.org/projects/shopkeepers/issues/380

**Originally posted by Wubsx (Mar 31, 2016):** 

What steps will reproduce the problem?
1. Using a villager spawn egg to try to edit a villagers stock
2. Server console throws error
3.What is the expected output? What do you see instead?
Server console throws error.What version of the product are you using?
1.70, Latest spigot version for 1.9Do you have an error log of what happened?
[19:49:28 ERROR]: Could not pass event PlayerInteractEvent to Shopkeepers v1.70 org.bukkit.event.EventException at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.jar:git-Spigot-1a196e1-6f032cd] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.jar:git-Spigot-1a196e1-6f032cd] at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd] at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:226) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd] at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:482) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd] at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:840) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd] at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:55) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd] at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:11) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd] at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72] at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72] at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd] at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd] at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd] at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd] at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.jar:git-Spigot-1a196e1-6f032cd] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72] Caused by: java.lang.NoSuchMethodError: org.bukkit.event.player.PlayerInteractEvent.getHand()Lorg/bukkit/inventory/EquipmentSlot; at com.nisovin.shopkeepers.compat.v1_9_R1.NMSHandler.isMainHandInteraction(NMSHandler.java:325) ~[?:?] at com.nisovin.shopkeepers.CreateListener.onPlayerInteract(CreateListener.java:81) ~[?:?] at sun.reflect.GeneratedMethodAccessor109.invoke(Unknown Source) ~[?:?] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72] at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72] at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-1a196e1-6f032cd] ... 17 morePlease provide any additional information below.

**Comment by blablubbabcDEV** [comment]
**Originally commented by blablubbabc (Mar 31, 2016):** 

Update your spigot server to a more recent version of spigot 1.9
