### ISSUE TITLE
Unable to access Shops

### ISSUE THREAD

**Issue by blablubbabcDEV** [Shopkeepers/Shopkeepers#391]
**Migrated from:** https://dev.bukkit.org/projects/shopkeepers/issues/390

**Originally posted by shaliquinn (Apr 15, 2016):** 

What steps will reproduce the problem?
1. Make admin shop (only one I use on our server)
2. Shift + Right click - worked fine till 1.9 update
3. Error report from debug shows in console. As no access is given....What is the expected output? What do you see instead?
I would expect to have the interface show up to edit my shops. Or buy from them.. or welp anything from them...What version of the product are you using?
Latest Version (Did a fresh install twice)Do you have an error log of what happened?
~~~Yes, This is with Debug enabled. To simplify...(hopefully)~~~
15.04 11:34:58 [Server] INFO ... 15 more
15.04 11:34:58 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot19.jar:git-Spigot-7d15d07-c194444]
15.04 11:34:58 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_72]
15.04 11:34:58 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_72]
15.04 11:34:58 [Server] INFO at sun.reflect.GeneratedMethodAccessor189.invoke(Unknown Source) ~[?:?]
15.04 11:34:58 [Server] INFO at com.nisovin.shopkeepers.LivingEntityShopListener.onEntityInteract(LivingEntityShopListener.java:56) ~[?:?]
15.04 11:34:58 [Server] INFO at com.nisovin.shopkeepers.compat.v1_9_R1.NMSHandler.isMainHandInteraction(NMSHandler.java:330) ~[?:?]
15.04 11:34:58 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.event.player.PlayerInteractEntityEvent.getHand()Lorg/bukkit/inventory/EquipmentSlot;
15.04 11:34:58 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_72]
15.04 11:34:58 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554) [Spigot19.jar:git-Spigot-7d15d07-c194444]
15.04 11:34:58 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655) [Spigot19.jar:git-Spigot-7d15d07-c194444]
15.04 11:34:58 [Server] INFO at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [Spigot19.jar:git-Spigot-7d15d07-c194444]
15.04 11:34:58 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:716) [Spigot19.jar:git-Spigot-7d15d07-c194444]
15.04 11:34:58 [Server] INFO at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [Spigot19.jar:git-Spigot-7d15d07-c194444]
15.04 11:34:58 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_72]
15.04 11:34:58 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_72]
15.04 11:34:58 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot19.jar:git-Spigot-7d15d07-c194444]
15.04 11:34:58 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInUseEntity.a(SourceFile:12) [Spigot19.jar:git-Spigot-7d15d07-c194444]
15.04 11:34:58 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInUseEntity.a(SourceFile:68) [Spigot19.jar:git-Spigot-7d15d07-c194444]
15.04 11:34:58 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1484) [Spigot19.jar:git-Spigot-7d15d07-c194444]
15.04 11:34:58 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot19.jar:git-Spigot-7d15d07-c194444]
15.04 11:34:58 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot19.jar:git-Spigot-7d15d07-c194444]
15.04 11:34:58 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot19.jar:git-Spigot-7d15d07-c194444]
15.04 11:34:58 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[Spigot19.jar:git-Spigot-7d15d07-c194444]
15.04 11:34:58 [Server] INFO org.bukkit.event.EventException
15.04 11:34:58 [Server] ERROR Could not pass event PlayerInteractEntityEvent to Shopkeepers v1.70
15.04 11:34:58 [Server] INFO Player Shaliquinn is interacting with entity at Location{world=CraftWorld{name=CoolWhip},x=118.5,y=86.0,z=-59.5,pitch=2.1275473,yaw=0.0}
15.04 11:34:58 [Server] INFO ... 39 more
15.04 11:34:58 [Server] INFO at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:228)
15.04 11:34:58 [Server] INFO at com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:369)
15.04 11:34:58 [Server] INFO Caused by: java.lang.IllegalArgumentException: Unable to find a field tracker with the type net.minecraft.server.v1_9_R1.Entity in net.minecraft.server.v1_9_R1.EntityTrackerEntry
15.04 11:34:58 [Server] INFO ... 37 more
15.04 11:34:58 [Server] INFO at com.comphenix.protocol.wrappers.BukkitConverters$13.getSpecificValue(BukkitConverters.java:693)
15.04 11:34:58 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:982)
15.04 11:34:58 [Server] INFO at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:243)
15.04 11:34:58 [Server] INFO Caused by: FieldAccessException: Cannot find entity from ID 6649.
15.04 11:34:58 [Server] INFO at java.lang.Thread.run(Unknown Source)
15.04 11:34:58 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
15.04 11:34:58 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264)
15.04 11:34:58 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326)
15.04 11:34:58 [Server] INFO at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722)
15.04 11:34:58 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
15.04 11:34:58 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
15.04 11:34:58 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
15.04 11:34:58 [Server] INFO at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
15.04 11:34:58 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
15.04 11:34:58 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
15.04 11:34:58 [Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
15.04 11:34:58 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
15.04 11:34:58 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
15.04 11:34:58 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
15.04 11:34:58 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
15.04 11:34:58 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
15.04 11:34:58 [Server] INFO at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$4.channelRead(NettyChannelInjector.java:278)
15.04 11:34:58 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
15.04 11:34:58 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
15.04 11:34:58 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
15.04 11:34:58 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
15.04 11:34:58 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
15.04 11:34:58 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149)
15.04 11:34:58 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249)
15.04 11:34:58 [Server] INFO at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.decode(NettyChannelInjector.java:546)
15.04 11:34:58 [Server] INFO at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.onPacketReceiving(NettyProtocolInjector.java:297)
15.04 11:34:58 [Server] INFO at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.packetReceived(NettyProtocolInjector.java:332)
15.04 11:34:58 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:606)
15.04 11:34:58 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:639)
15.04 11:34:58 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67)
15.04 11:34:58 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114)
15.04 11:34:58 [Server] INFO at me.libraryaddict.disguise.utilities.PacketsManager$1.onPacketReceiving(PacketsManager.java:90)
15.04 11:34:58 [Server] INFO at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:197)
15.04 11:34:58 [Server] INFO at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:229)
15.04 11:34:58 [Server] INFO at com.comphenix.protocol.wrappers.BukkitConverters$IgnoreNullConverter.getSpecific(BukkitConverters.java:146)
15.04 11:34:58 [Server] INFO at com.comphenix.protocol.wrappers.BukkitConverters$13.getSpecificValue(BukkitConverters.java:678)
15.04 11:34:58 [Server] INFO at com.comphenix.protocol.wrappers.BukkitConverters$13.getSpecificValue(BukkitConverters.java:699)
15.04 11:34:58 [Server] INFO java.lang.RuntimeException: Cannot retrieve entity from ID.
15.04 11:34:58 [Server] INFO ... 39 more
15.04 11:34:58 [Server] INFO at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:228)
15.04 11:34:58 [Server] INFO at com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:369)
15.04 11:34:58 [Server] INFO Caused by: java.lang.IllegalArgumentException: Unable to find a field tracker with the type net.minecraft.server.v1_9_R1.Entity in net.minecraft.server.v1_9_R1.EntityTrackerEntry
15.04 11:34:58 [Server] INFO ... 37 more
15.04 11:34:58 [Server] INFO at com.comphenix.protocol.wrappers.BukkitConverters$13.getSpecificValue(BukkitConverters.java:693)
15.04 11:34:58 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:982)
15.04 11:34:58 [Server] INFO at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:243)
15.04 11:34:58 [Server] INFO Caused by: FieldAccessException: Cannot find entity from ID 6649.
15.04 11:34:58 [Server] INFO at java.lang.Thread.run(Unknown Source)
15.04 11:34:58 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
15.04 11:34:58 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264)
15.04 11:34:58 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326)
15.04 11:34:58 [Server] INFO at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722)
15.04 11:34:58 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
15.04 11:34:58 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
15.04 11:34:58 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
15.04 11:34:58 [Server] INFO at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
15.04 11:34:58 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
15.04 11:34:58 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
15.04 11:34:58 [Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
15.04 11:34:58 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
15.04 11:34:58 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
15.04 11:34:58 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
15.04 11:34:58 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
15.04 11:34:58 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
15.04 11:34:58 [Server] INFO at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$4.channelRead(NettyChannelInjector.java:278)
15.04 11:34:58 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
15.04 11:34:58 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
15.04 11:34:58 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
15.04 11:34:58 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
15.04 11:34:58 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
15.04 11:34:58 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149)
15.04 11:34:58 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249)
15.04 11:34:58 [Server] INFO at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.decode(NettyChannelInjector.java:546)
15.04 11:34:58 [Server] INFO at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.onPacketReceiving(NettyProtocolInjector.java:297)
15.04 11:34:58 [Server] INFO at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.packetReceived(NettyProtocolInjector.java:332)
15.04 11:34:58 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:606)
15.04 11:34:58 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:639)
15.04 11:34:58 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67)
15.04 11:34:58 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114)
15.04 11:34:58 [Server] INFO at me.libraryaddict.disguise.utilities.PacketsManager$1.onPacketReceiving(PacketsManager.java:90)
15.04 11:34:58 [Server] INFO at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:197)
15.04 11:34:58 [Server] INFO at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:229)
15.04 11:34:58 [Server] INFO at com.comphenix.protocol.wrappers.BukkitConverters$IgnoreNullConverter.getSpecific(BukkitConverters.java:146)
15.04 11:34:58 [Server] INFO at com.comphenix.protocol.wrappers.BukkitConverters$13.getSpecificValue(BukkitConverters.java:678)
15.04 11:34:58 [Server] INFO at com.comphenix.protocol.wrappers.BukkitConverters$13.getSpecificValue(BukkitConverters.java:699)
15.04 11:34:58 [Server] INFO java.lang.RuntimeException: Cannot retrieve entity from ID.Clear logPlease provide any additional information below.
That is the code given when I Shift+Rightclick, This is after a fresh install of both the .jar and deletion of the folder literally just the one test shop made atm.
I am sure this may be my fault somehow as is the norm! but I cant figure out what?! :O)Â  So help pretty please (oh and thank you!)

**Comment by blablubbabcDEV** [comment]
**Originally commented by blablubbabc (Apr 15, 2016):** 

You have to update your spigot server. Shopkeepers requires a more recent version of spigot for MC 1.9.

**Comment by blablubbabcDEV** [comment]
**Originally closed by blablubbabc (Apr 15, 2016)**
