### ISSUE TITLE
Shopkeerper error

### ISSUE THREAD

**Issue by blablubbabcDEV** [Shopkeepers/Shopkeepers#40]
**Migrated from:** https://dev.bukkit.org/projects/shopkeepers/issues/30

**Originally posted by Ralf122 (Sep 2, 2012):** 

I got this error after the new update. so i downgraded also got it. everything works fine. but when you pay you can't get the item in your inventory it will be placed back automaticly.org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:144)
02.09 20:24:00 [Server] INFOÂ Â  Â  at java.lang.Class.forName(Class.java:264)
02.09 20:24:00 [Server] INFOÂ Â  Â  at java.lang.Class.forName0(Native Method)
02.09 20:24:00 [Server] INFOÂ Â  Â  at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
02.09 20:24:00 [Server] INFOÂ Â  Â  at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
02.09 20:24:00 [Server] INFOÂ Â  Â  at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:29)
02.09 20:24:00 [Server] INFOÂ Â  Â  at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:44)
02.09 20:24:00 [Server] INFOÂ Â  Â  at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
02.09 20:24:00 [Server] INFOÂ Â  Â  at java.security.AccessController.doPrivileged(Native Method)
02.09 20:24:00 [Server] INFOÂ Â  Â  at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
02.09 20:24:00 [Server] INFOÂ Â  Â  at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
02.09 20:24:00 [Server] INFOÂ Â  Â  at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
02.09 20:24:00 [Server] INFOÂ Â  Â  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
02.09 20:24:00 [Server] INFOÂ Â  Â  at java.lang.ClassLoader.defineClass(ClassLoader.java:634)
02.09 20:24:00 [Server] INFOÂ Â  Â  at java.lang.ClassLoader.defineClass1(Native Method)
02.09 20:24:00 [Server] INFO Caused by: java.lang.UnsupportedClassVersionError: me/dragon252525/emeraldMarket/EmeraldMarket : Unsupported major.minor version 51.0
02.09 20:24:00 [Server] INFOÂ Â  Â  at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
02.09 20:24:00 [Server] INFOÂ Â  Â  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:406)
02.09 20:24:00 [Server] INFOÂ Â  Â  at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:474)
02.09 20:24:00 [Server] INFOÂ Â  Â  at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
02.09 20:24:00 [Server] INFOÂ Â  Â  at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:578)
02.09 20:24:00 [Server] INFOÂ Â  Â  at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
02.09 20:24:00 [Server] INFOÂ Â  Â  at net.minecraft.server.ServerConnection.b(SourceFile:35)
02.09 20:24:00 [Server] INFOÂ Â  Â  at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:109)
02.09 20:24:00 [Server] INFOÂ Â  Â  at net.minecraft.server.NetworkManager.b(NetworkManager.java:276)
02.09 20:24:00 [Server] INFOÂ Â  Â  at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:44)
02.09 20:24:00 [Server] INFOÂ Â  Â  at net.minecraftserverhook.NetServerHandlerProxy.a(NetServerHandlerProxy.java:124)
02.09 20:24:00 [Server] INFOÂ Â  Â  at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:808)
02.09 20:24:00 [Server] INFOÂ Â  Â  at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:826)
02.09 20:24:00 [Server] INFOÂ Â  Â  at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:880)
02.09 20:24:00 [Server] INFOÂ Â  Â  at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:492)
02.09 20:24:00 [Server] INFOÂ Â  Â  at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
02.09 20:24:00 [Server] INFOÂ Â  Â  at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:21)
02.09 20:24:00 [Server] INFOÂ Â  Â  at org.bukkit.Bukkit.reload(Bukkit.java:183)
02.09 20:24:00 [Server] INFOÂ Â  Â  at org.bukkit.craftbukkit.CraftServer.reload(CraftServer.java:565)
02.09 20:24:00 [Server] INFOÂ Â  Â  at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:222)
02.09 20:24:00 [Server] INFOÂ Â  Â  at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:230)
02.09 20:24:00 [Server] INFOÂ Â  Â  at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:305)
02.09 20:24:00 [Server] INFOÂ Â  Â  at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:155)
02.09 20:24:00 [Server] INFO org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: me/dragon252525/emeraldMarket/EmeraldMarket : Unsupported major.minor version 51.0
02.09 20:24:00 [Server] SEVERE Could not load 'plugins/EmeraldMarket_v1.2_5.jar' in folder 'plugins'

**Comment by blablubbabcDEV** [comment]
**Originally commented by nisovin (Sep 2, 2012):** 

This is not a Shopkeepers error, it's an EmeraldMarket error.

**Comment by blablubbabcDEV** [comment]
**Originally commented by Ralf122 (Sep 3, 2012):** 

sorry that's the wrong error. that was a plugin I didn't even use is now removed.
this the error. 
03.09 09:08:43 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:330)
03.09 09:08:43 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:616)
03.09 09:08:43 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03.09 09:08:43 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
03.09 09:08:43 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
03.09 09:08:43 [Server] INFO at com.nisovin.shopkeepers.ShopListener.onEntityInteract(ShopListener.java:77)
03.09 09:08:43 [Server] INFO at com.nisovin.shopkeepers.Shopkeeper.updateRecipes(Shopkeeper.java:254)
03.09 09:08:43 [Server] INFO Caused by: java.lang.NoClassDefFoundError: com/nisovin/shopkeepers/ShopRecipe
03.09 09:08:43 [Server] INFO at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
03.09 09:08:43 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:406)
03.09 09:08:43 [Server] INFO at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:474)
03.09 09:08:43 [Server] INFO at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
03.09 09:08:43 [Server] INFO at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:578)
03.09 09:08:43 [Server] INFO at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
03.09 09:08:43 [Server] INFO at net.minecraft.server.ServerConnection.b(SourceFile:35)
03.09 09:08:43 [Server] INFO at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:109)
03.09 09:08:43 [Server] INFO at net.minecraft.server.NetworkManager.b(NetworkManager.java:276)
03.09 09:08:43 [Server] INFO at net.minecraft.server.Packet7UseEntity.handle(SourceFile:36)
03.09 09:08:43 [Server] INFO at net.minecraftserverhook.NetServerHandlerProxy.a(NetServerHandlerProxy.java:160)
03.09 09:08:43 [Server] INFO at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:1000)
03.09 09:08:43 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
03.09 09:08:43 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
03.09 09:08:43 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
03.09 09:08:43 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:332)
03.09 09:08:43 [Server] INFO org.bukkit.event.EventException
03.09 09:08:43 [Server] SEVERE Could not pass event PlayerInteractEntityEvent to Shopkeepers

**Comment by blablubbabcDEV** [comment]
**Originally commented by nisovin (Sep 3, 2012):** 

Try redownloading the plugin.

**Comment by blablubbabcDEV** [comment]
**Originally commented by Ralf122 (Sep 3, 2012):** 

@nisovin:
I installed everything again and made shops again. it worked a few times but later on i have the same problem.

**Comment by blablubbabcDEV** [comment]
**Originally commented by Ralf122 (Sep 3, 2012):** 

I've fixed it. I had no space in the chests for the emeralds. :)

**Comment by blablubbabcDEV** [comment]
**Originally closed by nisovin (Sep 10, 2012)**
