### ISSUE TITLE
Pls Help Im op but it says sry but...

### ISSUE THREAD

**Issue by blablubbabcDEV** [Shopkeepers/Shopkeepers#441]
**Migrated from:** https://dev.bukkit.org/projects/shopkeepers/issues/440

**Originally posted by MineRedFlitte (Nov 6, 2016):** 

What is the issue?
no permiddion
Please provide any additional information below.[01:59:21 INFO]: zUnleqitServer issued server command: /shopkeeper
>
[01:59:21 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'shopkeeper' in plugin Shopkeepers v1.78
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-952179b-f98775c]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-952179b-f98775c]
at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot.jar:git-Spigot-952179b-f98775c]
at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [spigot.jar:git-Spigot-952179b-f98775c]
at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [spigot.jar:git-Spigot-952179b-f98775c]
at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot.jar:git-Spigot-952179b-f98775c]
at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot.jar:git-Spigot-952179b-f98775c]
at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot.jar:git-Spigot-952179b-f98775c]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:685) [spigot.jar:git-Spigot-952179b-f98775c]
at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-952179b-f98775c]
at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot.jar:git-Spigot-952179b-f98775c]
at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot.jar:git-Spigot-952179b-f98775c]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.getTargetBlock(Ljava/util/Set;I)Lorg/bukkit/block/Block;
at com.nisovin.shopkeepers.CommandManager.onCommand(CommandManager.java:441) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-952179b-f98775c]
... 14 more

**Comment by blablubbabcDEV** [comment]
**Originally commented by blablubbabc (Nov 6, 2016):** 

No idea about the 'no permission' issue, but that error could mean that there is something wrong with your version of spigot. Maybe try a later version of spigot.

**Comment by blablubbabcDEV** [comment]
**Originally closed by blablubbabc (Dec 8, 2016)**
