### ISSUE TITLE
Trade impossible

### ISSUE THREAD

**Issue by blablubbabcDEV** [Shopkeepers/Shopkeepers#460]
**Migrated from:** https://dev.bukkit.org/projects/shopkeepers/issues/520

**Originally posted by allen (Mar 21, 2017):** 

hi,
Â 
Everything is good in the config. I can't set shop and change price..etc but when I right click on the NPC for trade. Nothing appears except a big message in the console :
Â 
Spoiler (click to show)
[11:44:26 ERROR]: Could not pass event PlayerInteractEntityEvent to Shopkeepers v1.81
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[craftbukkit.jar:git-Spigot-d60de0a-a951a88]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-d60de0a-a951a88]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-d60de0a-a951a88]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-d60de0a-a951a88]
at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1518) [craftbukkit.jar:git-Spigot-d60de0a-a951a88]
at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(SourceFile:69) [craftbukkit.jar:git-Spigot-d60de0a-a951a88]
at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(SourceFile:13) [craftbukkit.jar:git-Spigot-d60de0a-a951a88]
at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-d60de0a-a951a88]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_71]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_71]
at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [craftbukkit.jar:git-Spigot-d60de0a-a951a88]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [craftbukkit.jar:git-Spigot-d60de0a-a951a88]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [craftbukkit.jar:git-Spigot-d60de0a-a951a88]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [craftbukkit.jar:git-Spigot-d60de0a-a951a88]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [craftbukkit.jar:git-Spigot-d60de0a-a951a88]
at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]
Caused by: java.lang.NoSuchMethodError: org.bukkit.Bukkit.createMerchant(Ljava/lang/String;)Lorg/bukkit/inventory/Merchant;
at com.nisovin.shopkeepers.compat.v1_11_R1.NMSHandler.openTradeWindow(NMSHandler.java:42) ~[?:?]
at com.nisovin.shopkeepers.ui.defaults.TradingHandler.openWindow(TradingHandler.java:63) ~[?:?]
at com.nisovin.shopkeepers.ui.UIManager.requestUI(UIManager.java:77) ~[?:?]
at com.nisovin.shopkeepers.Shopkeeper.openWindow(Shopkeeper.java:422) ~[?:?]
at com.nisovin.shopkeepers.Shopkeeper.openTradingWindow(Shopkeeper.java:446) ~[?:?]
at com.nisovin.shopkeepers.Shopkeeper.onPlayerInteraction(Shopkeeper.java:543) ~[?:?]
at com.nisovin.shopkeepers.shoptypes.PlayerShopkeeper.onPlayerInteraction(PlayerShopkeeper.java:452) ~[?:?]
at com.nisovin.shopkeepers.LivingEntityShopListener.onEntityInteract(LivingEntityShopListener.java:58) ~[?:?]
at sun.reflect.GeneratedMethodAccessor166.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[craftbukkit.jar:git-Spigot-d60de0a-a951a88]
... 15 more

Â Any ideas ? 
Have a good day ;-)

**Comment by blablubbabcDEV** [comment]
**Originally commented by blablubbabc (Mar 21, 2017):** 

You have to update your server. Shopkeepers is using API which isn't yet available in your version of spigot.

**Comment by blablubbabcDEV** [comment]
**Originally commented by allen (Apr 1, 2017):** 

thx problem solved !

**Comment by blablubbabcDEV** [comment]
**Originally closed by blablubbabc (Mar 21, 2017)**
