### ISSUE TITLE
the shop keeper does not work...

### ISSUE THREAD

**Issue by blablubbabcDEV** [Shopkeepers/Shopkeepers#463]
**Migrated from:** https://dev.bukkit.org/projects/shopkeepers/issues/523

**Originally posted by TheLonelyJoe (Apr 2, 2017):** 

so i type /shopkeeper, the shop keeper spawns, i press shift and add items for trade and everything goes good so far but if any player tries to trade it just doesn't work i press the shopkeeper and nothing shows Â up and sometimes it shows the default trading that villagers usually have
any help please ....

**Comment by blablubbabcDEV** [comment]
**Originally commented by blablubbabc (Apr 8, 2017):** 

Check your server log for any errors. Also try updating your spigot server.
            Edited Apr 8, 2017

**Comment by blablubbabcDEV** [comment]
**Originally commented by TheLonelyJoe (Apr 9, 2017):** 

[23:12:04] [Server thread/INFO]: TheLonelyJoe issued server command: /shopkeeper
[23:12:13] [Server thread/WARN]: [Shopkeepers] Â§bShopkeepers needs an update.
[23:12:13] [Server thread/WARN]: [Shopkeepers] Â§bShopkeepers needs an update.
Â that's what it shows in the log file
i will try to update the plugin and come back here and tell you if it works
            Edited Apr 9, 2017

**Comment by blablubbabcDEV** [comment]
**Originally commented by TheLonelyJoe (Apr 9, 2017):** 

[23:18:42] [Server thread/ERROR]: Could not pass event PlayerInteractEntityEvent to Shopkeepers v1.81
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot59.jar:git-Spigot-16c940b-0805f60]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot59.jar:git-Spigot-16c940b-0805f60]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot59.jar:git-Spigot-16c940b-0805f60]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot59.jar:git-Spigot-16c940b-0805f60]
at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1518) [spigot59.jar:git-Spigot-16c940b-0805f60]
at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(SourceFile:69) [spigot59.jar:git-Spigot-16c940b-0805f60]
at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(SourceFile:13) [spigot59.jar:git-Spigot-16c940b-0805f60]
at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot59.jar:git-Spigot-16c940b-0805f60]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot59.jar:git-Spigot-16c940b-0805f60]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot59.jar:git-Spigot-16c940b-0805f60]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot59.jar:git-Spigot-16c940b-0805f60]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot59.jar:git-Spigot-16c940b-0805f60]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot59.jar:git-Spigot-16c940b-0805f60]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NoSuchMethodError: org.bukkit.Bukkit.createMerchant(Ljava/lang/String;)Lorg/bukkit/inventory/Merchant;
at com.nisovin.shopkeepers.compat.v1_11_R1.NMSHandler.openTradeWindow(NMSHandler.java:42) ~[?:?]
at com.nisovin.shopkeepers.ui.defaults.TradingHandler.openWindow(TradingHandler.java:63) ~[?:?]
at com.nisovin.shopkeepers.ui.UIManager.requestUI(UIManager.java:77) ~[?:?]
at com.nisovin.shopkeepers.Shopkeeper.openWindow(Shopkeeper.java:422) ~[?:?]
at com.nisovin.shopkeepers.Shopkeeper.openTradingWindow(Shopkeeper.java:446) ~[?:?]
at com.nisovin.shopkeepers.Shopkeeper.onPlayerInteraction(Shopkeeper.java:543) ~[?:?]
at com.nisovin.shopkeepers.LivingEntityShopListener.onEntityInteract(LivingEntityShopListener.java:58) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot59.jar:git-Spigot-16c940b-0805f60]
... 15 more
Â this is what shows up when i try to open the merchant ... i tryed to trade log for stone and it did not worked when i pressed the shopkeeper this shows up in the log and the villager has the default trade not the one i put there ...Â 
            Edited Apr 9, 2017

**Comment by blablubbabcDEV** [comment]
**Originally commented by blablubbabc (Apr 10, 2017):** 

You need to update your spigot server. Shopkeepers is using a function which is not yet available at the version of spigot you are using.
            Edited Apr 10, 2017

**Comment by blablubbabcDEV** [comment]
**Originally closed by blablubbabc (Apr 10, 2017)**
