### ISSUE TITLE
Problem with enchanted items

### ISSUE THREAD

**Issue by blablubbabcDEV** [Shopkeepers/Shopkeepers#472]
**Migrated from:** https://dev.bukkit.org/projects/shopkeepers/issues/532

**Originally posted by Glorlyg (Aug 17, 2017):** 

Hi!
Â 
We got this error message from server console. You can see it in the spoiler. We could see this error when we wanted to buy or sell enchanted items. How can we handel this error?
Â 
We use Shopkeeper v1.31.
Server version: CraftBukkit version git-Spigot-1.7.9-R0.2-204-g534549b (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)
We are a Hungarian 1.7.10 SMP server - YodaCraft Nostalgia (go.yodacraft.hu) .
Â 
Thanks for your fantastic work!
We are looking forward for your response. Thanks in advance!
Spoiler (click to show)
org.bukkit.event.EventException
 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[minecraft.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) [minecraft.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [minecraft.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
 at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:1477) [minecraft.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
 at net.minecraft.server.v1_7_R4.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:15) [minecraft.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
 at net.minecraft.server.v1_7_R4.PacketPlayInWindowClick.handle(PacketPlayInWindowClick.java:65) [minecraft.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
 at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [minecraft.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
 at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [minecraft.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
 at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [minecraft.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
 at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [minecraft.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
 at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [minecraft.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
 at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [minecraft.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
 at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [minecraft.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/inventory/meta/BannerMeta
 at com.nisovin.shopkeepers.Utils.areSimilarReasoned(Utils.java:369) ~[?:?]
 at com.nisovin.shopkeepers.Utils.areSimilar(Utils.java:125) ~[?:?]
 at com.nisovin.shopkeepers.ui.defaults.TradingHandler.itemEqualsAtLeast(TradingHandler.java:191) ~[?:?]
 at com.nisovin.shopkeepers.ui.defaults.TradingHandler.onInventoryClick(TradingHandler.java:114) ~[?:?]
 at com.nisovin.shopkeepers.ui.UIListener.onInventoryClick(UIListener.java:52) ~[?:?]
 at sun.reflect.GeneratedMethodAccessor518.invoke(Unknown Source) ~[?:?]
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
 at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[minecraft.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
 ... 13 more

**Comment by blablubbabcDEV** [comment]
**Originally commented by Glorlyg (Aug 23, 2017):** 

Thank you for your effort!
