### ISSUE TITLE
command /shopkeepers doesnt work

### ISSUE THREAD

**Issue by Pyrocringe** [Shopkeepers/Shopkeepers#492]
I need help... ive been trying to solve this for a time now and... yeah well...

This happen on the server console:
[00:04:15 INFO]: Pyrocringe issued server command: /shopkeepers
[00:04:15 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'shopkeepers' in plugin Shopkeepers v1.86
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit.jar:git-Spigot-da32fe1-df0b4c1]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[craftbukkit.jar:git-Spigot-da32fe1-df0b4c1]
at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:643) ~[craftbukkit.jar:git-Spigot-da32fe1-df0b4c1]
at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1083) [craftbukkit.jar:git-Spigot-da32fe1-df0b4c1]
at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:918) [craftbukkit.jar:git-Spigot-da32fe1-df0b4c1]
at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [craftbukkit.jar:git-Spigot-da32fe1-df0b4c1]
at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [craftbukkit.jar:git-Spigot-da32fe1-df0b4c1]
at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [craftbukkit.jar:git-Spigot-da32fe1-df0b4c1]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:686) [craftbukkit.jar:git-Spigot-da32fe1-df0b4c1]
at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [craftbukkit.jar:git-Spigot-da32fe1-df0b4c1]
at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:627) [craftbukkit.jar:git-Spigot-da32fe1-df0b4c1]
at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:530) [craftbukkit.jar:git-Spigot-da32fe1-df0b4c1]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.getTargetBlock(Ljava/util/Set;I)Lorg/bukkit/block/Block;
at com.nisovin.shopkeepers.CommandManager.onCommand(CommandManager.java:469) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Spigot-da32fe1-df0b4c1]
... 14 more

and this happens in game:
An internal error occured while attempting to perform this command

**Comment by blablubbabc** [comment]
The Shopkeeper plugin version you are using is incompatible with the specific spigot server version you are using. Either downgrade shopkeepers, or upgrade your spigot server (recommended).
