### ISSUE TITLE
Shopkeepers 1.13 "Disabled"

### ISSUE THREAD

**Issue by CaptainAmpersand** [Shopkeepers/Shopkeepers#513]
## When reporting an issue:
* Provide the versions you are using of Minecraft, Spigot and Shopkeepers.
* Provide a detailed description of your problem and add as much information as possible which could help reproducing the issue.
* If possible, include **step-by-step instructions** on how to reproduce the issue on a fresh Spigot server.
Using CraftBukkit version git-Spigot-69774b3-2ba567f (MC: 1.13)
Trying to enable shopkeepers in the slightest will give me this error.
[03:38:57 INFO]: MrAmpersand issued server command: /shopkeepers
[03:38:57 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'shopkeepers' in plugin Shopkeepers v2.2.1 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:36) ~[server.jar:git-Spigot-69774b3-2ba567f]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-69774b3-2ba567f]
        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:693) ~[server.jar:git-Spigot-69774b3-2ba567f]
        at net.minecraft.server.v1_13_R1.PlayerConnection.handleCommand(PlayerConnection.java:1634) ~[server.jar:git-Spigot-69774b3-2ba567f]
        at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1469) ~[server.jar:git-Spigot-69774b3-2ba567f]
        at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[server.jar:git-Spigot-69774b3-2ba567f]
        at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[server.jar:git-Spigot-69774b3-2ba567f]
        at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[server.jar:git-Spigot-69774b3-2ba567f]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
        at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [server.jar:git-Spigot-69774b3-2ba567f]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [server.jar:git-Spigot-69774b3-2ba567f]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [server.jar:git-Spigot-69774b3-2ba567f]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [server.jar:git-Spigot-69774b3-2ba567f]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [server.jar:git-Spigot-69774b3-2ba567f]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

**Comment by CaptainAmpersand** [comment]
```[03:38:24] [Server thread/INFO]: [Shopkeepers] Enabling Shopkeepers v2.2.1
[03:38:24] [Server thread/ERROR]: [Shopkeepers] Potentially incompatible server version: v1_13_R1
[03:38:24] [Server thread/ERROR]: [Shopkeepers] Shopkeepers is trying to run in 'compatibility mode'.
[03:38:24] [Server thread/INFO]: [Shopkeepers] Check for updates at: http://dev.bukkit.org/server-mods/shopkeepers/
[03:38:24] [Server thread/ERROR]: [Shopkeepers] Incompatible server version: Shopkeepers cannot be enabled.```

**Comment by CaptainAmpersand** [comment]
Oh, that's why.
Your "ver 2.3.0" build downloads 2.2.1.
That should fix some stuff if done :P
