### ISSUE TITLE
shopkeeper reload error

### ISSUE THREAD

**Issue by mckite** [Shopkeepers/Shopkeepers#522]
Shopkeepers :  1.86
MC 1.12.2

[13:34:56 INFO]: This server is running CraftBukkit version git-Spigot-642f6d2-6103339 (MC:
rsion 1.12.2-R0.1-SNAPSHOT)

[13:33:17 INFO]: KitePro issued server command: /shopkeepers reload
[13:33:17 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'shopkeepers' in
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit.ja

        at com.massivecraft.massivelag.inject.MassiveLagCommandMap.dispatch(MassiveLagComma
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648
t-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.ja
-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [cr
6d2-6103339]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [craf
2-6103339]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [craft
-6103339]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftb
6103339]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_181
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_181]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [craftbukkit.jar:git-
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [craft
-6103339]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [craft
-6103339]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [craft
-6103339]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [cra
d2-6103339]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:1.8.0_181]
        at java.util.HashMap$KeyIterator.next(Unknown Source) ~[?:1.8.0_181]
        at com.nisovin.shopkeepers.ui.UIManager.closeAll(UIManager.java:143) ~[?:?]
        at com.nisovin.shopkeepers.ShopkeepersPlugin.onDisable(ShopkeepersPlugin.java:397)
        at com.nisovin.shopkeepers.ShopkeepersPlugin.reload(ShopkeepersPlugin.java:446) ~[?
        at com.nisovin.shopkeepers.CommandManager.onCommand(CommandManager.java:96) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.ja

        ... 15 more

**Comment by blablubbabc** [comment]
Will be fixed with the next update (I will probably release a v2.2.2 to fix this for pre MC 1.13 versions as well).
