### ISSUE TITLE
The plugin is not working

### ISSUE THREAD

**Issue by DjGamerDz** [Shopkeepers/Shopkeepers#526]
## Preliminaries:

* **Shopkeepers version:** `<2.2.2>`
* **Spigot version:** `<[13:31:53 INFO]: This server is running CraftBukkit version git-Spigot-2440e18-4228a56 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
[13:31:53 INFO]: Checking version, please wait...
[13:31:55 INFO]: You are 41 version(s) behind>`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was **`<able / not able>`** to reproduce my issue on a freshly setup and up-to-date Spigot server (currently **`<[13:31:53 INFO]: This server is running CraftBukkit version git-Spigot-2440e18-4228a56 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
[13:31:53 INFO]: Checking version, please wait...
[13:31:55 INFO]: You are 41 version(s) behind>`**) with the latest version of Shopkeepers (currently **`<2.2.2>`**), with no other plugins and with no kinds of other server or client mods.

## The issue:

I have a problem with the plugin, i cant use it and its red on plugins list.
The output of /shopkeeper command is:

[13:30:46 WARN]: Unexpected exception while parsing console command "shopkeeper"
org.bukkit.command.CommandException: Cannot execute command 'shopkeeper' in plugin Shopkeepers v2.2.2 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:36) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:695) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:680) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
        at net.minecraft.server.v1_13_R2.DedicatedServer.aU(DedicatedServer.java:453) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:412) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]

My plugins list:

Plugins (16): SkinsRestorer, WorldEdit, PrivateChests, LandClaiming, GlobalMarket, RandomTeleport, OnePlayerSleep, EssentialsPro, PowerRanks, Vault, FreeTeleport, PvPToggle, Shopkeepers, AuthMe, Jobs, DecoHeads

**Comment by blablubbabc** [comment]
You are using the wrong plugin version for your spigot server version. Version 2.2.2 only supports MC up to 1.12.2. For MC 1.13.1 use v2.4.1 of Shopkeepers.

It should also mention that the Shopkeepers version your are using is incompatible with your server version inside your server log, when it tries to start the plugin.

**Comment by DjGamerDz** [comment]
ok
