### ISSUE TITLE
Plugin won't activated on 1.13.2

### ISSUE THREAD

**Issue by VMBindraban** [Shopkeepers/Shopkeepers#530]
## Preliminaries:

* **Shopkeepers version:** `2.2.2`
* **Spigot version:** `git-Spigot-a1ba5fe-3359cb1 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was **`able`** to reproduce my issue on a freshly setup and up-to-date Spigot server (currently **`1.13.2`**) with the latest version of Shopkeepers (currently **`2.2.2`**), with no other plugins and with no kinds of other server or client mods.

## The issue:

Provide a detailed description of your problem and add as much information as possible which could help reproducing the issue.

Include:
Start server.

```
org.bukkit.command.CommandException: Cannot execute command 'shopkeeper' in plugin Shopkeepers v2.2.2 - plugin is disabled.
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:36) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:699) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1646) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1481) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514) [?:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
at java.lang.Thread.run(Thread.java:844) [?:?]
```

**Comment by blablubbabc** [comment]
v2.2.2 is not the latest version of Shopkeepers / not compatible with 1.13.x. 
Try v2.4.1 (https://dev.bukkit.org/projects/shopkeepers/files/2615781). This one should work on 1.13.x. If it doesn't, let me know again.
I have promoted it from 'beta' to 'release' to make it more visible. It was 'beta' before because Spigot 1.13 wasn't really stable yet when it got released.
