### ISSUE TITLE
1.14.1 bug

### ISSUE THREAD

**Issue by successed** [Shopkeepers/Shopkeepers#566]
shoppekers version 2.6.0
paper version is latest 1.14.1 #42

This shopkeepers villagers is spawning villagers..

Problem picture : http://prntscr.com/nt9nip

**Comment by successed** [comment]
http://prntscr.com/nt9ppk

**Comment by successed** [comment]
http://prntscr.com/nt9qde

**Comment by successed** [comment]
[23:11:48] [Server thread/ERROR]: Could not pass event InventoryClickEvent to Shopkeepers v2.6.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[paperclip.jar:git-Spigot-03bd4b0-17da342]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paperclip.jar:git-Spigot-03bd4b0-17da342]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) ~[paperclip.jar:git-Spigot-03bd4b0-17da342]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) ~[paperclip.jar:git-Spigot-03bd4b0-17da342]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2158) ~[paperclip.jar:git-Spigot-03bd4b0-17da342]
	at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[paperclip.jar:git-Spigot-03bd4b0-17da342]
	at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[paperclip.jar:git-Spigot-03bd4b0-17da342]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[paperclip.jar:git-Spigot-03bd4b0-17da342]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [paperclip.jar:git-Spigot-03bd4b0-17da342]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [paperclip.jar:git-Spigot-03bd4b0-17da342]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [paperclip.jar:git-Spigot-03bd4b0-17da342]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [paperclip.jar:git-Spigot-03bd4b0-17da342]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:895) [paperclip.jar:git-Spigot-03bd4b0-17da342]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888) [paperclip.jar:git-Spigot-03bd4b0-17da342]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:99) [paperclip.jar:git-Spigot-03bd4b0-17da342]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:871) [paperclip.jar:git-Spigot-03bd4b0-17da342]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:805) [paperclip.jar:git-Spigot-03bd4b0-17da342]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.Inventory.getTitle()Ljava/lang/String;
	at com.nisovin.shopkeepers.ui.UIListener.onInventoryClick(UIListener.java:91) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor254.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[paperclip.jar:git-Spigot-03bd4b0-17da342]
	... 17 more

**Comment by blablubbabc** [comment]
* For the future: Please try to reproduce your issues with Spigot. Paper has additional changes on top of Spigot which makes it harder for me to pin down the underlying issue.
* As mentioned in its description (https://dev.bukkit.org/projects/shopkeepers/files), Shopkeepers v2.6.0 is not compatible with Minecraft 1.14. Please wait for an official update.

**Comment by successed** [comment]
> * For the future: Please try to reproduce your issues with Spigot. Paper has additional changes on top of Spigot which makes it harder for me to pin down the underlying issue.
> * As mentioned in its description (https://dev.bukkit.org/projects/shopkeepers/files), Shopkeepers v2.6.0 is not compatible with Minecraft 1.14. Please wait for an official update.

why you close it before you fix the problem?

**Comment by blablubbabc** [comment]
There is already an open issue regarding the update for 1.14: https://github.com/Shopkeepers/Shopkeepers/issues/564
