### ISSUE TITLE
Could not pass event InventoryClickEvent to Shopkeepers v2.7.2

### ISSUE THREAD

**Issue by Leonardo-Fiori** [Shopkeepers/Shopkeepers#583]
## Preliminaries:

* **Shopkeepers version:** `2.7.2`
* **Spigot version:** `This server is running Paper version git-Paper-97 (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)`
---

## The issue:

I randomly got this error message in console. Could not find a way to reproduce it.

[11:20:25 ERROR]: Could not pass event InventoryClickEvent to Shopkeepers v2.7.2
java.lang.NoSuchMethodError: net.minecraft.server.v1_14_R1.EntityPlayer.openTrade(ILnet/minecraft/server/v1_14_R1/MerchantRecipeList;IIZZ)V
        at com.nisovin.shopkeepers.compat.v1_14_R1.NMSHandler.updateTrades(NMSHandler.java:172) ~[?:?]
        at com.nisovin.shopkeepers.ui.defaults.TradingHandler.updateTrades(TradingHandler.java:230) ~[?:?]
        at com.nisovin.shopkeepers.ui.defaults.TradingHandler.onInventoryClickLate(TradingHandler.java:325) ~[?:?]
        at com.nisovin.shopkeepers.ui.UIListener.onInventoryClickLate(UIListener.java:144) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.14.2.jar:git-Paper-97]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.2.jar:git-Paper-97]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.2.jar:git-Paper-97]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2342) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:999) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:992) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:115) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:976) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:909) ~[patched_1.14.2.jar:git-Paper-97]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[11:20:32 ERROR]: Could not pass event InventoryClickEvent to Shopkeepers v2.7.2
java.lang.NoSuchMethodError: net.minecraft.server.v1_14_R1.EntityPlayer.openTrade(ILnet/minecraft/server/v1_14_R1/MerchantRecipeList;IIZZ)V
        at com.nisovin.shopkeepers.compat.v1_14_R1.NMSHandler.updateTrades(NMSHandler.java:172) ~[?:?]
        at com.nisovin.shopkeepers.ui.defaults.TradingHandler.updateTrades(TradingHandler.java:230) ~[?:?]
        at com.nisovin.shopkeepers.ui.defaults.TradingHandler.onInventoryClickLate(TradingHandler.java:325) ~[?:?]
        at com.nisovin.shopkeepers.ui.UIListener.onInventoryClickLate(UIListener.java:144) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.14.2.jar:git-Paper-97]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.2.jar:git-Paper-97]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.2.jar:git-Paper-97]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2342) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:999) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:992) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:115) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:976) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:909) ~[patched_1.14.2.jar:git-Paper-97]
        at java.lang.Thread.run(Thread.java:834) [?:?]

After console error the plugin seems to be still working. I wonder what is it!

The only thing that i changed recently on the server was setting up an iptables firewall.. don't know if this can be related to the issue.

**Comment by blablubbabc** [comment]
Shopkeepers v2.7.2 only supports MC 1.14.**3**.
