### ISSUE TITLE
Using a shopkeeper in snapshot for minecraft 1.4.4

### ISSUE THREAD

**Issue by blablubbabcDEV** [Shopkeepers/Shopkeepers#60]
**Migrated from:** https://dev.bukkit.org/projects/shopkeepers/issues/50

**Originally posted by Dommbringer (Nov 14, 2012):** 

2012-11-14 15:47:50 [SEVERE] Could not pass event PlayerInteractEntityEvent to Shopkeepers v1.9
org.bukkit.event.EventException
Â  Â  at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:341)
Â  Â  at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
Â  Â  at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
Â  Â  at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
Â  Â  at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:1032)
Â  Â  at net.minecraft.server.Packet7UseEntity.handle(SourceFile:36)
Â  Â  at net.minecraft.server.NetworkManager.b(NetworkManager.java:290)
Â  Â  at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:112)
Â  Â  at net.minecraft.server.ServerConnection.b(SourceFile:39)
Â  Â  at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
Â  Â  at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:595)
Â  Â  at net.minecraft.server.DedicatedServer.r(DedicatedServer.java:222)
Â  Â  at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:493)
Â  Â  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:426)
Â  Â  at net.minecraft.server.ThreadServerApplication.run(SourceFile:856)
Caused by: java.lang.NoSuchMethodError: net.minecraft.server.EntityVillager.c(Lnet/minecraft/server/EntityHuman;)Z
Â  Â  at com.nisovin.shopkeepers.VolatileCode.openTradeWindow(VolatileCode.java:60)
Â  Â  at com.nisovin.shopkeepers.ShopkeepersPlugin.openTradeWindow(ShopkeepersPlugin.java:520)
Â  Â  at com.nisovin.shopkeepers.VillagerListener.onEntityInteract(VillagerListener.java:68)
Â  Â  at sun.reflect.GeneratedMethodAccessor193.invoke(Unknown Source)
Â  Â  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Â  Â  at java.lang.reflect.Method.invoke(Method.java:616)
Â  Â  at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:339)
Â  Â  ... 14 morePlease provide any additional information below.

**Comment by blablubbabcDEV** [comment]
**Originally commented by BEQOsNtDi6xRDGzqIAT7 (Nov 14, 2012):** 

Confirmed. The error is thrown when right-clicking a shopkeeper in 1.4.4.
Creation and setup (shift-right-click) of a shopkeeper continues to work. 

            Edited Nov 14, 2012

**Comment by blablubbabcDEV** [comment]
**Originally closed by nisovin (Nov 17, 2012)**
