### ISSUE TITLE
Could not pass event InventoryClickEvent to Shopkeepers v1.9

### ISSUE THREAD

**Issue by blablubbabcDEV** [Shopkeepers/Shopkeepers#62]
**Migrated from:** https://dev.bukkit.org/projects/shopkeepers/issues/52

**Originally posted by BEQOsNtDi6xRDGzqIAT7 (Nov 16, 2012):** 

Using the latest 1.9 dev build for 1.4.4, this error pops up when successfully trading with a shopkeeper. Specifically, when removing the sold item.00:31:24 [SEVERE] Could not pass event InventoryClickEvent to Shopkeepers v1.9
org.bukkit.event.EventException
Â  Â  Â  Â  at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:341)
Â  Â  Â  Â  at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
Â  Â  Â  Â  at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
Â  Â  Â  Â  at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
Â  Â  Â  Â  at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:1145)
Â  Â  Â  Â  at net.minecraft.server.Packet102WindowClick.handle(SourceFile:31)
Â  Â  Â  Â  at net.minecraft.server.NetworkManager.b(NetworkManager.java:290)
Â  Â  Â  Â  at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:112)
Â  Â  Â  Â  at net.minecraft.server.ServerConnection.b(SourceFile:39)
Â  Â  Â  Â  at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
Â  Â  Â  Â  at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:595)
Â  Â  Â  Â  at net.minecraft.server.DedicatedServer.r(DedicatedServer.java:222)
Â  Â  Â  Â  at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:493)
Â  Â  Â  Â  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:426)
Â  Â  Â  Â  at net.minecraft.server.ThreadServerApplication.run(SourceFile:856)
Caused by: java.lang.NullPointerException
Â  Â  Â  Â  at com.nisovin.shopkeepers.ShopListener.onInventoryClick(ShopListener.java:161)
Â  Â  Â  Â  at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
Â  Â  Â  Â  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Â  Â  Â  Â  at java.lang.reflect.Method.invoke(Method.java:601)
Â  Â  Â  Â  at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:339)
Â  Â  Â  Â  ... 14 more

**Comment by blablubbabcDEV** [comment]
**Originally commented by nisovin (Nov 17, 2012):** 

I've uploaded a new version that should fix this.

**Comment by blablubbabcDEV** [comment]
**Originally commented by BEQOsNtDi6xRDGzqIAT7 (Nov 17, 2012):** 

@nisovin:
Confirmed to work.

**Comment by blablubbabcDEV** [comment]
**Originally closed by nisovin (Nov 17, 2012)**
