### ISSUE TITLE
Spigot 1.15.2

### ISSUE THREAD

**Issue by Blueeyestar** [Shopkeepers/Shopkeepers#626]
And again a new version has been released. Unfortunately, as always, not compatible with some plugins. Unfortunately, the shopkeeper is also back. Please adjust :) Thank you

[23:30:26] [Server thread/ERROR]: Error occurred while enabling Shopkeepers v2.9.0 (Is it up to date?)
java.lang.NoSuchMethodError: net.minecraft.server.v1_15_R1.EntityRaider.u(Z)V
	at com.nisovin.shopkeepers.compat.v1_15_R1.NMSHandler.setCanJoinRaid(NMSHandler.java:128) ~[?:?]
	at com.nisovin.shopkeepers.shopobjects.living.SKLivingShopObject.spawn(SKLivingShopObject.java:218) ~[?:?]
	at com.nisovin.shopkeepers.shopkeeper.SKShopkeeperRegistry.spawnShopkeeper(SKShopkeeperRegistry.java:834) ~[?:?]
	at com.nisovin.shopkeepers.shopkeeper.SKShopkeeperRegistry.addShopkeeper(SKShopkeeperRegistry.java:449) ~[?:?]
	at com.nisovin.shopkeepers.shopkeeper.SKShopkeeperRegistry.loadShopkeeper(SKShopkeeperRegistry.java:397) ~[?:?]
	at com.nisovin.shopkeepers.storage.SKShopkeeperStorage.doReload(SKShopkeeperStorage.java:368) ~[?:?]
	at com.nisovin.shopkeepers.storage.SKShopkeeperStorage.reload(SKShopkeeperStorage.java:262) ~[?:?]
	at com.nisovin.shopkeepers.SKShopkeepersPlugin.onEnable(SKShopkeepersPlugin.java:386) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[minecraft_server.jar:git-Spigot-800b93f-dad6176]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [minecraft_server.jar:git-Spigot-800b93f-dad6176]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [minecraft_server.jar:git-Spigot-800b93f-dad6176]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:462) [minecraft_server.jar:git-Spigot-800b93f-dad6176]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:376) [minecraft_server.jar:git-Spigot-800b93f-dad6176]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457) [minecraft_server.jar:git-Spigot-800b93f-dad6176]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:267) [minecraft_server.jar:git-Spigot-800b93f-dad6176]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [minecraft_server.jar:git-Spigot-800b93f-dad6176]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]

**Comment by blablubbabc** [comment]
Try this (untested) snapshot: https://nexus.lichtspiele.org/repository/snapshots/com/nisovin/shopkeepers/Shopkeepers/2.9.1-SNAPSHOT/Shopkeepers-2.9.1-20200121.231151-1.jar

**Comment by Blueeyestar** [comment]
Super seems to be working. I will now do a long-term test with it. Great that you are so fast :)

**Comment by blablubbabc** [comment]
Fixed in v2.9.1
