### ISSUE TITLE
Could not pass event PlayerInteractEntityEvent - 1.4.4

### ISSUE THREAD

**Issue by blablubbabcDEV** [Shopkeepers/Shopkeepers#65]
**Migrated from:** https://dev.bukkit.org/projects/shopkeepers/issues/55

**Originally posted by KBKWilliamsson (Nov 18, 2012):** 

What steps will reproduce the problem?
1. Attempt to open trade with shopkeeper
2. Look at the console
(It's however possible to shift-click and open that inventory)What version of the product are you using?
Shopkeeper 1.8
Minecraft 1.4.4
craftbukkit-1.4.5-R0.1Â  (build #2480)Do you have an error log of what happened?
2012-11-18 18:57:08 [SEVERE] Could not pass event PlayerInteractEntityEvent to Shopkeepers v1.8
org.bukkit.event.EventException
Â  Â  at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:341)
Â  Â  at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
Â  Â  at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
Â  Â  at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
Â  Â  at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:1092)
Â  Â  at net.minecraft.server.Packet7UseEntity.handle(SourceFile:36)
Â  Â  at net.minecraft.server.NetworkManager.b(NetworkManager.java:290)
Â  Â  at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:113)
Â  Â  at net.minecraft.server.ServerConnection.b(SourceFile:39)
Â  Â  at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
Â  Â  at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:595)
Â  Â  at net.minecraft.server.DedicatedServer.r(DedicatedServer.java:222)
Â  Â  at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:493)
Â  Â  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:426)
Â  Â  at net.minecraft.server.ThreadServerApplication.run(SourceFile:856)
Caused by: java.lang.NoSuchMethodError: net.minecraft.server.EntityVillager.c(Lnet/minecraft/server/EntityHuman;)Z
Â  Â  at com.nisovin.shopkeepers.ShopkeepersPlugin.openTradeWindow(ShopkeepersPlugin.java:540)
Â  Â  at com.nisovin.shopkeepers.VillagerListener.onEntityInteract(VillagerListener.java:68)
Â  Â  at sun.reflect.GeneratedMethodAccessor166.invoke(Unknown Source)
Â  Â  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
Â  Â  at java.lang.reflect.Method.invoke(Unknown Source)
Â  Â  at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:339)
Â  Â  ... 14 more

**Comment by blablubbabcDEV** [comment]
**Originally commented by BEQOsNtDi6xRDGzqIAT7 (Nov 18, 2012):** 

...1.8? Try the 1.9 dev version.

**Comment by blablubbabcDEV** [comment]
**Originally commented by KBKWilliamsson (Nov 18, 2012):** 

@BEQOsNtDi6xRDGzqIAT7:
I quickly looked at the files and saw that there wasn't a dev build posted, so I missed the link. I posted the ticket in a hurry, I'll try that out. Thanks.

**Comment by blablubbabcDEV** [comment]
**Originally commented by KBKWilliamsson (Nov 18, 2012):** 

Not an issue in the 1.9 dev build, my bad for missing the link to it. Please remove ticket.

**Comment by blablubbabcDEV** [comment]
**Originally closed by KBKWilliamsson (Nov 18, 2012)**
