### ISSUE TITLE
Could not pass event InventoryClickEvent (v1.9pre)

### ISSUE THREAD

**Issue by blablubbabcDEV** [Shopkeepers/Shopkeepers#66]
**Migrated from:** https://dev.bukkit.org/projects/shopkeepers/issues/56

**Originally posted by CubeNation (Nov 20, 2012):** 

Here's the stack trace for the problem:12:47:25 [SEVERE] Could not pass event InventoryClickEvent to Shopkeepers v1.9
org.bukkit.event.EventException
Â  Â  Â  Â  at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:341)
Â  Â  Â  Â  at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
Â  Â  Â  Â  at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
Â  Â  Â  Â  at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
Â  Â  Â  Â  at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:1213)
Â  Â  Â  Â  at net.minecraft.server.Packet102WindowClick.handle(SourceFile:31)
Â  Â  Â  Â  at net.minecraft.server.NetworkManager.b(NetworkManager.java:290)
Â  Â  Â  Â  at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:113)
Â  Â  Â  Â  at net.minecraft.server.ServerConnection.b(SourceFile:39)
Â  Â  Â  Â  at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
Â  Â  Â  Â  at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:595)
Â  Â  Â  Â  at net.minecraft.server.DedicatedServer.r(DedicatedServer.java:222)
Â  Â  Â  Â  at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:493)
Â  Â  Â  Â  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:426)
Â  Â  Â  Â  at net.minecraft.server.ThreadServerApplication.run(SourceFile:856)
Caused by: java.lang.NullPointerException
Â  Â  Â  Â  at com.nisovin.shopkeepers.ShopListener.onInventoryClick(ShopListener.java:161)
Â  Â  Â  Â  at sun.reflect.GeneratedMethodAccessor127.invoke(Unknown Source)
Â  Â  Â  Â  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
Â  Â  Â  Â  at java.lang.reflect.Method.invoke(Unknown Source)
Â  Â  Â  Â  at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:339)
Â  Â  Â  Â  ... 14 more

**Comment by blablubbabcDEV** [comment]
**Originally commented by BEQOsNtDi6xRDGzqIAT7 (Nov 20, 2012):** 

Doesn't mean much if you don't say what Minecraft/bukkit version you're using this with.

**Comment by blablubbabcDEV** [comment]
**Originally commented by nisovin (Nov 20, 2012):** 

This was fixed a couple days ago, please re-download the dev build.

**Comment by blablubbabcDEV** [comment]
**Originally commented by CubeNation (Dec 3, 2012):** 

Seems to be working. Thx!

**Comment by blablubbabcDEV** [comment]
**Originally closed by nisovin (Nov 27, 2012)**
