### ISSUE TITLE
unable to trade with shopkeepers

### ISSUE THREAD

**Issue by blablubbabcDEV** [Shopkeepers/Shopkeepers#67]
**Migrated from:** https://dev.bukkit.org/projects/shopkeepers/issues/57

**Originally posted by mindflay8 (Nov 21, 2012):** 

I can sneak click villagers to set up a shop but can't click on them to trade.Â  When i try i get an error message.Â  I've attempted this with an OP and non-OP user with the same result.What version of the product are you using?craftbukkit-1.4.5-R0-2
shopkeepers v1.9Do you have an error log of what happened?07:02:51 [SEVERE] Could not pass event PlayerInteractEntityEvent to Shopkeepers v1.9
org.bukkit.event.EventException
Â  Â  Â  Â  at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:341)
Â  Â  Â  Â  at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
Â  Â  Â  Â  at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
Â  Â  Â  Â  at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
Â  Â  Â  Â  at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:1105)
Â  Â  Â  Â  at net.minecraft.server.Packet7UseEntity.handle(SourceFile:36)
Â  Â  Â  Â  at net.minecraft.server.NetworkManager.b(NetworkManager.java:290)
Â  Â  Â  Â  at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:113)
Â  Â  Â  Â  at net.minecraft.server.ServerConnection.b(SourceFile:39)
Â  Â  Â  Â  at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
Â  Â  Â  Â  at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:595)
Â  Â  Â  Â  at net.minecraft.server.DedicatedServer.r(DedicatedServer.java:222)
Â  Â  Â  Â  at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:493)
Â  Â  Â  Â  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:426)
Â  Â  Â  Â  at net.minecraft.server.ThreadServerApplication.run(SourceFile:856)
Caused by: java.lang.NoSuchMethodError: net.minecraft.server.EntityVillager.c(Lnet/minecraft/server/EntityHuman;)Z
Â  Â  Â  Â  at com.nisovin.shopkeepers.VolatileCode.openTradeWindow(VolatileCode.java:60)
Â  Â  Â  Â  at com.nisovin.shopkeepers.ShopkeepersPlugin.openTradeWindow(ShopkeepersPlugin.java:520)
Â  Â  Â  Â  at com.nisovin.shopkeepers.VillagerListener.onEntityInteract(VillagerListener.java:68)
Â  Â  Â  Â  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Â  Â  Â  Â  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
Â  Â  Â  Â  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Â  Â  Â  Â  at java.lang.reflect.Method.invoke(Method.java:616)
Â  Â  Â  Â  at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:339)
Â  Â  Â  Â  ... 14 morePlease provide any additional information below.other plugins on the server...
ChunkAutoClaimer
Creeperheal
Transporter
Vault
Simple-AutoSaveconfig.yml file settings...disable-other-villagers: true
block-villager-spawns: false
enable-spawn-verifier: false
enable-purchase-logging: false
save-instantly: trueenable-world-guard-restrictions: false
enable-towny-restrictions: falsecreate-player-shop-with-command: true
simulate-right-click-on-command: true
allow-custom-quantities: true
protect-chests: true
max-shops-per-player: 0
max-chest-distance: 15enable-villager-shops: true
create-player-shop-with-egg: true
deleting-player-shop-returns-egg: falseenable-sign-shops: true
sign-shop-first-line: "[SHOP]"
sign-shop-creation-item: 388
sign-shop-creation-item-data: 0editor-title: "Shopkeeper Editor"
save-item: 133
delete-item: 51currency-item: 388
currency-item-data: 0
zero-item: 341high-currency-item: 133
high-currency-item-data: 0
high-currency-value: 9
high-currency-min-cost: 20
high-zero-item: 341language: en

**Comment by blablubbabcDEV** [comment]
**Originally closed by mindflay8 (Nov 21, 2012)**
