### ISSUE TITLE
1.17.1 Problem

### ISSUE THREAD

**Issue by Blueeyestar** [Shopkeepers/Shopkeepers#757]
**Shopkeeper has the following problem in the latest version 1.17.1**

[18:26:20] [Server thread/ERROR]: Error occurred while enabling Shopkeepers v2.13.1 (Is it up to date?)
java.lang.NoSuchFieldError: bO
	at com.nisovin.shopkeepers.compat.v1_17_R1.NMSHandler.overwriteLivingEntityAI(NMSHandler.java:69) ~[?:?]
	at com.nisovin.shopkeepers.shopobjects.living.SKLivingShopObject.overwriteAI(SKLivingShopObject.java:345) ~[?:?]
	at com.nisovin.shopkeepers.shopobjects.living.SKLivingShopObject.spawn(SKLivingShopObject.java:269) ~[?:?]
	at com.nisovin.shopkeepers.shopkeeper.SKShopkeeperRegistry.spawnShopkeeper(SKShopkeeperRegistry.java:1184) ~[?:?]
	at com.nisovin.shopkeepers.shopkeeper.SKShopkeeperRegistry.addShopkeeper(SKShopkeeperRegistry.java:620) ~[?:?]
	at com.nisovin.shopkeepers.shopkeeper.SKShopkeeperRegistry.loadShopkeeper(SKShopkeeperRegistry.java:540) ~[?:?]
	at com.nisovin.shopkeepers.storage.SKShopkeeperStorage.doReload(SKShopkeeperStorage.java:520) ~[?:?]
	at com.nisovin.shopkeepers.storage.SKShopkeeperStorage.reload(SKShopkeeperStorage.java:414) ~[?:?]
	at com.nisovin.shopkeepers.SKShopkeepersPlugin.onEnable(SKShopkeepersPlugin.java:335) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[server.jar:3171-Spigot-610a8c0-fb556bf]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[server.jar:3171-Spigot-610a8c0-fb556bf]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[server.jar:3171-Spigot-610a8c0-fb556bf]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495) ~[server.jar:3171-Spigot-610a8c0-fb556bf]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409) ~[server.jar:3171-Spigot-610a8c0-fb556bf]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:604) ~[server.jar:3171-Spigot-610a8c0-fb556bf]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:266) ~[server.jar:3171-Spigot-610a8c0-fb556bf]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:995) ~[server.jar:3171-Spigot-610a8c0-fb556bf]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[server.jar:3171-Spigot-610a8c0-fb556bf]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by CloudeLecaw** [comment]
i can agree this one looks simliar.

```
[07:20:57] [Server thread/ERROR]: Error occurred while enabling Shopkeepers v2.13.1 (Is it up to date?)
java.lang.NoSuchFieldError: bO
	at com.nisovin.shopkeepers.compat.v1_17_R1.NMSHandler.overwriteLivingEntityAI(NMSHandler.java:69) ~[?:?]
	at com.nisovin.shopkeepers.shopobjects.living.SKLivingShopObject.overwriteAI(SKLivingShopObject.java:345) ~[?:?]
	at com.nisovin.shopkeepers.shopobjects.living.SKLivingShopObject.spawn(SKLivingShopObject.java:269) ~[?:?]
	at com.nisovin.shopkeepers.shopkeeper.SKShopkeeperRegistry.spawnShopkeeper(SKShopkeeperRegistry.java:1184) ~[?:?]
	at com.nisovin.shopkeepers.shopkeeper.SKShopkeeperRegistry.addShopkeeper(SKShopkeeperRegistry.java:620) ~[?:?]
	at com.nisovin.shopkeepers.shopkeeper.SKShopkeeperRegistry.loadShopkeeper(SKShopkeeperRegistry.java:540) ~[?:?]
	at com.nisovin.shopkeepers.storage.SKShopkeeperStorage.doReload(SKShopkeeperStorage.java:520) ~[?:?]
	at com.nisovin.shopkeepers.storage.SKShopkeeperStorage.reload(SKShopkeeperStorage.java:414) ~[?:?]
	at com.nisovin.shopkeepers.SKShopkeepersPlugin.onEnable(SKShopkeepersPlugin.java:335) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[server.jar:3172-Spigot-610a8c0-99561c2]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[server.jar:3172-Spigot-610a8c0-99561c2]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[server.jar:3172-Spigot-610a8c0-99561c2]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495) ~[server.jar:3172-Spigot-610a8c0-99561c2]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409) ~[server.jar:3172-Spigot-610a8c0-99561c2]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:604) ~[server.jar:3172-Spigot-610a8c0-99561c2]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:266) ~[server.jar:3172-Spigot-610a8c0-99561c2]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:995) ~[server.jar:3172-Spigot-610a8c0-99561c2]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[server.jar:3172-Spigot-610a8c0-99561c2]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by CloudeLecaw** [comment]
Its me aggain...
the issue could might has to do with citicens that is not loading correct,,,?....
see here from an other plugin called ccrides..
```

There we also find the magical

`[09:16:42] [Server thread/WARN]: Caused by: java.lang.NoSuchFieldError: bO`

```
[09:16:41] [Server thread/INFO]: [ccRides] Sign Config Loaded.
[09:16:42] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[09:16:42] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[09:16:42] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
[09:16:42] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[09:16:42] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[09:16:42] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[09:16:42] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_17_R1.entity.MobEntityController.createEntityFromClass(MobEntityController.java:48)
[09:16:42] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_17_R1.entity.MobEntityController.createEntity(MobEntityController.java:32)
[09:16:42] [Server thread/WARN]: 	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[09:16:42] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[09:16:42] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:159)
[09:16:42] [Server thread/WARN]: 	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59)
[09:16:42] [Server thread/WARN]: 	at net.citizensnpcs.Citizens$CitizensLoadTask.run(Citizens.java:501)
[09:16:42] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:81)
[09:16:42] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400)
[09:16:42] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1254)
[09:16:42] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438)
[09:16:42] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1202)
[09:16:42] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1035)
[09:16:42] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303)
[09:16:42] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[09:16:42] [Server thread/WARN]: Caused by: java.lang.NoSuchFieldError: bO
[09:16:42] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_17_R1.entity.EndermanController$EntityEndermanNPC.<init>(EndermanController.java:59)
[09:16:42] [Server thread/WARN]: 	... 20 more
```
```

**Comment by Jordan231111** [comment]
same issue here when updating to 1.17.1

**Comment by ic22487** [comment]
Same issue here - logged in to find villagers walking around in the shops with no trades lol
![2021-07-07_13 46 33](https://user-images.githubusercontent.com/61802721/124813842-ef385900-df2a-11eb-9e1c-78fff95133b7.png)

**Comment by Comquister** [comment]
[16:25:09 WARN]: [Shopkeepers] Task #90 for Shopkeepers v2.13.1 generated an exception
java.lang.NoSuchFieldError: bO
        at com.nisovin.shopkeepers.compat.v1_17_R1.NMSHandler.overwriteLivingEntityAI(NMSHandler.java:69) ~[?:?]
        at com.nisovin.shopkeepers.shopobjects.living.SKLivingShopObject.overwriteAI(SKLivingShopObject.java:345) ~[?:?]        at com.nisovin.shopkeepers.shopobjects.living.SKLivingShopObject.spawn(SKLivingShopObject.java:269) ~[?:?]
        at com.nisovin.shopkeepers.shopkeeper.SKShopkeeperRegistry.spawnShopkeeper(SKShopkeeperRegistry.java:1184) ~[?:?]
        at com.nisovin.shopkeepers.shopkeeper.ShopkeeperSpawnQueue.process(ShopkeeperSpawnQueue.java:57) ~[?:?]
        at com.nisovin.shopkeepers.shopkeeper.ShopkeeperSpawnQueue.process(ShopkeeperSpawnQueue.java:17) ~[?:?]
        at com.nisovin.shopkeepers.util.taskqueue.TaskQueue.execute(TaskQueue.java:192) ~[?:?]
        at com.nisovin.shopkeepers.shopkeeper.ShopkeeperSpawnQueue$SpawnerTask.run(ShopkeeperSpawnQueue.java:45) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.1.jar:git-Purpur-1259]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.1.jar:git-Purpur-1259]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1565) ~[patched_1.17.1.jar:git-Purpur-1259]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:492) ~[patched_1.17.1.jar:git-Purpur-1259]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1480) ~[patched_1.17.1.jar:git-Purpur-1259]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1270) ~[patched_1.17.1.jar:git-Purpur-1259]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1259]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[16:25:09 WARN]: [Shopkeepers] Task #90 for Shopkeepers v2.13.1 generated an exception
java.lang.NoSuchFieldError: bO
        at com.nisovin.shopkeepers.compat.v1_17_R1.NMSHandler.overwriteLivingEntityAI(NMSHandler.java:69) ~[?:?]
        at com.nisovin.shopkeepers.shopobjects.living.SKLivingShopObject.overwriteAI(SKLivingShopObject.java:345) ~[?:?]        at com.nisovin.shopkeepers.shopobjects.living.SKLivingShopObject.spawn(SKLivingShopObject.java:269) ~[?:?]
        at com.nisovin.shopkeepers.shopkeeper.SKShopkeeperRegistry.spawnShopkeeper(SKShopkeeperRegistry.java:1184) ~[?:?]
        at com.nisovin.shopkeepers.shopkeeper.ShopkeeperSpawnQueue.process(ShopkeeperSpawnQueue.java:57) ~[?:?]
        at com.nisovin.shopkeepers.shopkeeper.ShopkeeperSpawnQueue.process(ShopkeeperSpawnQueue.java:17) ~[?:?]
        at com.nisovin.shopkeepers.util.taskqueue.TaskQueue.execute(TaskQueue.java:192) ~[?:?]
        at com.nisovin.shopkeepers.shopkeeper.ShopkeeperSpawnQueue$SpawnerTask.run(ShopkeeperSpawnQueue.java:45) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.1.jar:git-Purpur-1259]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.1.jar:git-Purpur-1259]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1565) ~[patched_1.17.1.jar:git-Purpur-1259]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:492) ~[patched_1.17.1.jar:git-Purpur-1259]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1480) ~[patched_1.17.1.jar:git-Purpur-1259]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1270) ~[patched_1.17.1.jar:git-Purpur-1259]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1259]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[16:25:09 WARN]: [Shopkeepers] Task #90 for Shopkeepers v2.13.1 generated an exception
java.lang.NoSuchFieldError: bO
        at com.nisovin.shopkeepers.compat.v1_17_R1.NMSHandler.overwriteLivingEntityAI(NMSHandler.java:69) ~[?:?]
        at com.nisovin.shopkeepers.shopobjects.living.SKLivingShopObject.overwriteAI(SKLivingShopObject.java:345) ~[?:?]        at com.nisovin.shopkeepers.shopobjects.living.SKLivingShopObject.spawn(SKLivingShopObject.java:269) ~[?:?]
        at com.nisovin.shopkeepers.shopkeeper.SKShopkeeperRegistry.spawnShopkeeper(SKShopkeeperRegistry.java:1184) ~[?:?]
        at com.nisovin.shopkeepers.shopkeeper.ShopkeeperSpawnQueue.process(ShopkeeperSpawnQueue.java:57) ~[?:?]
        at com.nisovin.shopkeepers.shopkeeper.ShopkeeperSpawnQueue.process(ShopkeeperSpawnQueue.java:17) ~[?:?]
        at com.nisovin.shopkeepers.util.taskqueue.TaskQueue.execute(TaskQueue.java:192) ~[?:?]
        at com.nisovin.shopkeepers.shopkeeper.ShopkeeperSpawnQueue$SpawnerTask.run(ShopkeeperSpawnQueue.java:45) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.1.jar:git-Purpur-1259]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.1.jar:git-Purpur-1259]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1565) ~[patched_1.17.1.jar:git-Purpur-1259]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:492) ~[patched_1.17.1.jar:git-Purpur-1259]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1480) ~[patched_1.17.1.jar:git-Purpur-1259]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1270) ~[patched_1.17.1.jar:git-Purpur-1259]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1259]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by blablubbabc** [comment]
Compatibility for MC 1.17.1 has been added in Shopkeepers v2.13.2, which will be available for download shortly.
