### ISSUE TITLE
Plugin disabled 

### ISSUE THREAD

**Issue by Agent-of-SWORD** [Shopkeepers/Shopkeepers#759]
## Preliminaries:

* **Shopkeepers version:** `2.13.3
* **Spigot version:** `This server is running Paper version git-Paper-103 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 990f7da)
You are 9 version(s) behind
Previous version: git-Paper-352 (MC: 1.16.4)
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was **`<not able>`** to reproduce my issue on a freshly setup and up-to-date Spigot server (currently **`<Insert output of /version command on up-to-date Spigot server>`**) with the latest version of Shopkeepers (currently **`<Insert latest tested Shopkeepers version>`**), with no other plugins and with no kinds of other server or client mods.

## The issue:

Provide a detailed description of your problem and add as much information as possible which could help reproducing the issue.

Include:
* I am on Paper 1.17.1, IDK why the version command says I am on an old version. After I updated, all shopkeepers disappeared. So I downloaded and uploaded the latest Shopkeeper plugin file to the server plugin folder. I restarted but it still doesn't work. Typing in /shopkeeper says the plugin is disabled. I tried finding this issue on Google and your Known Issues and Wiki pages, to no avail. I searched in the config file for clues, didn't find anything. I have left the old Shopkeepers plugin file since I feared that deleting it prematurely might result in the loss of the save file with all my shopkeepers.
* Step-by-step instructions on how to reproduce the issue.
I do not have a separate Spigot server, so I cannot give any advice as to how to do this on a fresh Spigot server. 

* Error log on console:
* [18-07-2021 13:00:13] DK0010 issued server command: /shopkeeper
[18-07-2021 13:00:13] null
[18-07-2021 13:00:13] org.bukkit.command.CommandException: Cannot execute command 'shopkeeper' in plugin Shopkeepers v2.8.1 - plugin is disabled.
[18-07-2021 13:00:13] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.17.1.jar:git-Paper-103]
[18-07-2021 13:00:13] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-103]
[18-07-2021 13:00:13] at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[patched_1.17.1.jar:git-Paper-103]
[18-07-2021 13:00:13] at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2170) ~[?:?]
[18-07-2021 13:00:13] at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1981) ~[?:?]
[18-07-2021 13:00:13] at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1962) ~[?:?]
[18-07-2021 13:00:13] at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
[18-07-2021 13:00:13] at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[?:?]
[18-07-2021 13:00:13] at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:36) ~[?:?]
[18-07-2021 13:00:13] at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-103]
[18-07-2021 13:00:13] at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
[18-07-2021 13:00:13] at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
[18-07-2021 13:00:13] at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1348) ~[patched_1.17.1.jar:git-Paper-103]
[18-07-2021 13:00:13] at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:190) ~[patched_1.17.1.jar:git-Paper-103]
[18-07-2021 13:00:13] at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
[18-07-2021 13:00:13] at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1327) ~[patched_1.17.1.jar:git-Paper-103]
[18-07-2021 13:00:13] at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1320) ~[patched_1.17.1.jar:git-Paper-103]
[18-07-2021 13:00:13] at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:110) ~[?:?]
[18-07-2021 13:00:13] at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1458) ~[patched_1.17.1.jar:git-Paper-103]
[18-07-2021 13:00:13] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-103]
[18-07-2021 13:00:13] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-103]
[18-07-2021 13:00:13] at java.lang.Thread.run(Thread.java:831) [?:?]
* If modified from default: Plugin configurations.
* .. Anything else that might be useful to reproduce and identify the issue.

**Comment by blablubbabc** [comment]
> Shopkeepers v2.8.1
You are using an outdated shopkeepers version that is not compatible with MC 1.17.1. You need to use Shopkeepers v.2.13.3, which can be found here: https://dev.bukkit.org/projects/shopkeepers/files

Maybe you have left an old plugin jar on the server when you attempted to update. If you cannot identify the v2.8.1 plugin jar, you will have to check the contents of your other plugin jars to ensure that you have not accidentally renamed the old Shopkeepers plugin jar to something else.

For any issues caused by the plugin not being enabled: Your server log should also contain a section somewhere at the beginning when the plugin attempted to enable where it states that it could not be enabled, either due to an incompatible server version, or due to some error during the plugin startup procedure.

> I do not have a separate Spigot server, so I cannot give any advice as to how to do this on a fresh Spigot server.
While this has not been required to identify the issue here, for future issues, you can always setup a minimal server locally and try to reproduce the issue there. The effort to do this is comparatively low compared to the time that can be saved on my side debugging an issue. Which is why the issue template asks for this.
