### ISSUE TITLE
Error while enabling Shopkeeper

### ISSUE THREAD

**Issue by blablubbabcDEV** [Shopkeepers/Shopkeepers#76]
**Migrated from:** https://dev.bukkit.org/projects/shopkeepers/issues/66

**Originally posted by PhanaticD (Dec 9, 2012):** 

Happens with recent builds of craftbukkit2012-12-08 22:07:59 [INFO] [Shopkeepers] Enabling Shopkeepers v1.9
2012-12-08 22:07:59 [SEVERE] Error occurred while enabling Shopkeepers v1.9 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/EntityLiving
Â  Â  Â  Â  at com.nisovin.shopkeepers.shoptypes.AdminShopkeeper.loadItemStack(AdminShopkeeper.java:228)
Â  Â  Â  Â  at com.nisovin.shopkeepers.shoptypes.AdminShopkeeper.load(AdminShopkeeper.java:61)
Â  Â  Â  Â  at com.nisovin.shopkeepers.Shopkeeper.<init>(Shopkeeper.java:24)
Â  Â  Â  Â  at com.nisovin.shopkeepers.shoptypes.AdminShopkeeper.<init>(AdminShopkeeper.java:36)
Â  Â  Â  Â  at com.nisovin.shopkeepers.ShopkeepersPlugin.load(ShopkeepersPlugin.java:628)
Â  Â  Â  Â  at com.nisovin.shopkeepers.ShopkeepersPlugin.onEnable(ShopkeepersPlugin.java:91)
Â  Â  Â  Â  at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
Â  Â  Â  Â  at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374)
Â  Â  Â  Â  at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
Â  Â  Â  Â  at org.bukkit.craftbukkit.v1_4_5.CraftServer.loadPlugin(CraftServer.java:304)
Â  Â  Â  Â  at org.bukkit.craftbukkit.v1_4_5.CraftServer.enablePlugins(CraftServer.java:286)
Â  Â  Â  Â  at net.minecraft.server.v1_4_5.MinecraftServer.j(MinecraftServer.java:324)
Â  Â  Â  Â  at net.minecraft.server.v1_4_5.MinecraftServer.e(MinecraftServer.java:303)
Â  Â  Â  Â  at net.minecraft.server.v1_4_5.MinecraftServer.a(MinecraftServer.java:262)
Â  Â  Â  Â  at net.minecraft.server.v1_4_5.DedicatedServer.init(DedicatedServer.java:147)
Â  Â  Â  Â  at net.minecraft.server.v1_4_5.MinecraftServer.run(MinecraftServer.java:402)
Â  Â  Â  Â  at net.minecraft.server.v1_4_5.ThreadServerApplication.run(SourceFile:856)
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.EntityLiving
Â  Â  Â  Â  at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:34)
Â  Â  Â  Â  at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:29)
Â  Â  Â  Â  at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
Â  Â  Â  Â  at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
Â  Â  Â  Â  ... 17 more

**Comment by blablubbabcDEV** [comment]
**Originally commented by nisovin (Dec 26, 2012):** 

You need to update to one of the dev builds.

**Comment by blablubbabcDEV** [comment]
**Originally closed by nisovin (Dec 26, 2012)**
