### ISSUE TITLE
the plugin dont work 

### ISSUE THREAD

**Issue by WariAin** [Shopkeepers/Shopkeepers#761]
## Preliminaries:

* **Shopkeepers version:** `<2.13.1>`
* **Spigot version:** `<2.13.1>`

[23:22:08 ERROR]: Could not pass event PlayerInteractEvent to Shopkeepers v2.13.1
java.lang.NoSuchFieldError: bO
        at com.nisovin.shopkeepers.compat.v1_17_R1.NMSHandler.overwriteLivingEntityAI(NMSHandler.java:69) ~[Shopkeepers-2.13.1.jar:?]
        at com.nisovin.shopkeepers.shopobjects.living.SKLivingShopObject.overwriteAI(SKLivingShopObject.java:345) ~[Shopkeepers-2.13.1.jar:?]
        at com.nisovin.shopkeepers.shopobjects.living.SKLivingShopObject.spawn(SKLivingShopObject.java:269) ~[Shopkeepers-2.13.1.jar:?]
        at com.nisovin.shopkeepers.shopkeeper.SKShopkeeperRegistry.spawnShopkeeper(SKShopkeeperRegistry.java:1184) ~[Shopkeepers-2.13.1.jar:?]
        at com.nisovin.shopkeepers.shopkeeper.SKShopkeeperRegistry.addShopkeeper(SKShopkeeperRegistry.java:620) ~[Shopkeepers-2.13.1.jar:?]
        at com.nisovin.shopkeepers.shopkeeper.SKShopkeeperRegistry.createShopkeeper(SKShopkeeperRegistry.java:499) ~[Shopkeepers-2.13.1.jar:?]
        at com.nisovin.shopkeepers.shopkeeper.AbstractShopType.handleShopkeeperCreation(AbstractShopType.java:141) ~[Shopkeepers-2.13.1.jar:?]
        at com.nisovin.shopkeepers.SKShopkeepersPlugin.handleShopkeeperCreation(SKShopkeepersPlugin.java:589) ~[Shopkeepers-2.13.1.jar:?]
        at com.nisovin.shopkeepers.shopcreation.CreateListener.onPlayerInteract(CreateListener.java:275) ~[Shopkeepers-2.13.1.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.17.1.jar:git-Paper-172]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-172]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-172]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Paper-172]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:538) ~[patched_1.17.1.jar:git-Paper-172]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:510) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1723) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:33) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:9) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:36) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-172]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1348) ~[patched_1.17.1.jar:git-Paper-172]
        at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:190) ~[patched_1.17.1.jar:git-Paper-172]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1327) ~[patched_1.17.1.jar:git-Paper-172]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1320) ~[patched_1.17.1.jar:git-Paper-172]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1281) ~[patched_1.17.1.jar:git-Paper-172]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[patched_1.17.1.jar:git-Paper-172]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-172]
        at java.lang.Thread.run(Thread.java:831) [?:?] #757

**Comment by blablubbabc** [comment]
You need to use  v2.13.2 or later for MC 1.17.1 support. v2.13.1 only supports 1.17.
