### ISSUE TITLE
Cannot access sales

### ISSUE THREAD

**Issue by blablubbabcDEV** [Shopkeepers/Shopkeepers#77]
**Migrated from:** https://dev.bukkit.org/projects/shopkeepers/issues/67

**Originally posted by Marnixxie (Dec 15, 2012):** 

What steps will reproduce the problem?
1. Right click to check the sales of the shopkeeper
2.
3.What is the expected output? What do you see instead?Seeing the window of the sales, but I get nothing and an error instead.What version of the product are you using?CraftBukkit and Shopkeepers, both latest versiomDo you have an error log of what happened?Â  Â  Â  Â  at net.minecraft.server.Packet7UseEntity.handle(SourceFile:36)
Â  Â  Â  Â  at net.minecraft.server.NetworkManager.b(NetworkManager.java:290)
Â  Â  Â  Â  at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:112)
Â  Â  Â  Â  at net.minecraft.server.ServerConnection.b(SourceFile:39)
Â  Â  Â  Â  at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
Â  Â  Â  Â  at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:595)
Â  Â  Â  Â  at net.minecraft.server.DedicatedServer.r(DedicatedServer.java:222)
Â  Â  Â  Â  at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:493)
Â  Â  Â  Â  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:426)
Â  Â  Â  Â  at net.minecraft.server.ThreadServerApplication.run(SourceFile:856)
Caused by: java.lang.NoSuchMethodError: net.minecraft.server.EntityVillager.c(Lnet/minecraft/server/EntityHuman;)Z
Â  Â  Â  Â  at com.nisovin.shopkeepers.ShopkeepersPlugin.openTradeWindow(ShopkeepersPlugin.java:540)
Â  Â  Â  Â  at com.nisovin.shopkeepers.VillagerListener.onEntityInteract(VillagerListener.java:68)
Â  Â  Â  Â  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Â  Â  Â  Â  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
Â  Â  Â  Â  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
Â  Â  Â  Â  at java.lang.reflect.Method.invoke(Unknown Source)
Â  Â  Â  Â  at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:339)Please provide any additional information below.

**Comment by blablubbabcDEV** [comment]
**Originally commented by nisovin (Dec 16, 2012):** 

Don't ever say "latest version". Specify the versions you're using. The Shopkeepers version you're using is not compatible with the CraftBukkit version you're using.

**Comment by blablubbabcDEV** [comment]
**Originally commented by Marnixxie (Dec 16, 2012):** 

@nisovin:
Shopkeepers V1.9
CraftBukkit 1.4.5 R02
Pretty sure that both are the latest version?

**Comment by blablubbabcDEV** [comment]
**Originally commented by nisovin (Dec 20, 2012):** 

Are you running one of the 1.9 test builds or the official release build in the Files section?

**Comment by blablubbabcDEV** [comment]
**Originally closed by nisovin (Dec 26, 2012)**
