### ISSUE TITLE
Shopkeepers-1.10-test-2 Plugin Error.

### ISSUE THREAD

**Issue by blablubbabcDEV** [Shopkeepers/Shopkeepers#80]
**Migrated from:** https://dev.bukkit.org/projects/shopkeepers/issues/70

**Originally posted by Stormofblood (Dec 23, 2012):** 

What steps will reproduce the problem?
1. Unsure as to what is causing the problem, attempted to re-produce, error appears to be random.
2.
3.What is the expected output? What do you see instead?
Plugin appears to be working as it should.What version of the product are you using?
Shopkeepers-1.10-test-2.jarDo you have an error log of what happened?
2012-12-22 13:14:20 [SEVERE] Could not pass event PlayerInteractEvent to Shopkeepers v1.10.0
org.bukkit.event.EventException
Â  Â  at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
Â  Â  at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
Â  Â  at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
Â  Â  at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
Â  Â  at org.bukkit.craftbukkit.v1_4_6.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:178)
Â  Â  at net.minecraft.server.v1_4_6.PlayerInteractManager.interact(PlayerInteractManager.java:376)
Â  Â  at net.minecraft.server.v1_4_6.PlayerConnection.a(PlayerConnection.java:657)
Â  Â  at net.minecraft.server.v1_4_6.Packet15Place.handle(SourceFile:58)
Â  Â  at net.minecraft.server.v1_4_6.NetworkManager.b(NetworkManager.java:290)
Â  Â  at net.minecraft.server.v1_4_6.PlayerConnection.d(PlayerConnection.java:112)
Â  Â  at net.minecraft.server.v1_4_6.ServerConnection.b(SourceFile:39)
Â  Â  at net.minecraft.server.v1_4_6.DedicatedServerConnection.b(SourceFile:30)
Â  Â  at net.minecraft.server.v1_4_6.MinecraftServer.r(MinecraftServer.java:598)
Â  Â  at net.minecraft.server.v1_4_6.DedicatedServer.r(DedicatedServer.java:224)
Â  Â  at net.minecraft.server.v1_4_6.MinecraftServer.q(MinecraftServer.java:494)
Â  Â  at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:427)
Â  Â  at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:849)
Caused by: java.lang.IllegalArgumentException: Cannot measure distance between skyblock and spawn
Â  Â  at org.bukkit.Location.distanceSquared(Location.java:381)
Â  Â  at org.bukkit.Location.distance(Location.java:364)
Â  Â  at com.nisovin.shopkeepers.BlockListener.onPlayerInteract(BlockListener.java:115)
Â  Â  at sun.reflect.GeneratedMethodAccessor58.invoke(Unknown Source)
Â  Â  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
Â  Â  at java.lang.reflect.Method.invoke(Unknown Source)
Â  Â  at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
Â  Â  ... 16 morePlease provide any additional information below.I love this plugin very much, and i appreciate the hard work that has been put into it! :D

**Comment by blablubbabcDEV** [comment]
**Originally closed by nisovin (Mar 18, 2013)**
