### ISSUE TITLE
New version of shopkeepers

### ISSUE THREAD

**Issue by LordVoldigoad** [Shopkeepers/Shopkeepers#803]
hello, i´m a recent user of shoopkeepers and i´m hosting a server that uses the version 2.16.0 and i´m having a problem that is, that the plugin isnt working and i dont know really why its not working, this is what the server report says:
<html>
<body>

[23:16:57] [Server thread/ERROR]: [Shopkeepers] Failed to load the save file! Note: Server downgrades or manually editing the save file are not supported!
--
78 | com.nisovin.shopkeepers.util.data.persistence.InvalidDataFormatException: Failed to load data as Bukkit config!
79 | at com.nisovin.shopkeepers.util.data.persistence.bukkit.BukkitConfigDataStore.loadFromString(BukkitConfigDataStore.java:63) ~[Shopkeepers-2.16.0.jar:?]
80 | at com.nisovin.shopkeepers.util.data.persistence.DataStoreBase.load(DataStoreBase.java:58) ~[Shopkeepers-2.16.0.jar:?]
81 | at com.nisovin.shopkeepers.storage.SKShopkeeperStorage.doReload(SKShopkeeperStorage.java:456) ~[Shopkeepers-2.16.0.jar:?]
82 | at com.nisovin.shopkeepers.storage.SKShopkeeperStorage.reload(SKShopkeeperStorage.java:408) ~[Shopkeepers-2.16.0.jar:?]
83 | at com.nisovin.shopkeepers.SKShopkeepersPlugin.onEnable(SKShopkeepersPlugin.java:406) ~[Shopkeepers-2.16.0.jar:?]
84 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
85 | at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
86 | at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
87 | at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[paper-1.19.jar:git-Paper-44]
88 | at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[paper-1.19.jar:git-Paper-44]
89 | at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633) ~[paper-1.19.jar:git-Paper-44]
90 | at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419) ~[paper-1.19.jar:git-Paper-44]
91 | at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.jar:git-Paper-44]
92 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1121) ~[paper-1.19.jar:git-Paper-44]
93 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-44]
94 | at java.lang.Thread.run(Thread.java:833) ~[?:?]
95 | Caused by: org.bukkit.configuration.InvalidConfigurationException: Could not call method 'public static org.bukkit.inventory.meta.ItemMeta org.bukkit.craftbukkit.v1_19_R1.inventory.CraftMetaItem$SerializableMeta.deserialize(java.util.Map) throws java.lang.Throwable' of class org.bukkit.craftbukkit.v1_19_R1.inventory.CraftMetaItem$SerializableMeta for deserialization
96 | at com.nisovin.shopkeepers.util.bukkit.ConfigUtils.loadConfigSafely(ConfigUtils.java:247) ~[Shopkeepers-2.16.0.jar:?]
97 | at com.nisovin.shopkeepers.util.data.persistence.bukkit.BukkitConfigDataStore.loadFromString(BukkitConfigDataStore.java:61) ~[Shopkeepers-2.16.0.jar:?]
98 | ... 15 more
99 | Caused by: java.lang.IllegalArgumentException: The skull profile is missing a name or textures!
100 | at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.0.1-jre.jar:?]
101 | at org.bukkit.craftbukkit.v1_19_R1.profile.CraftPlayerProfile.validateSkullProfile(CraftPlayerProfile.java:38) ~[paper-1.19.jar:git-Paper-44]
102 | at org.bukkit.craftbukkit.v1_19_R1.inventory.CraftMetaSkull.setOwnerProfile(CraftMetaSkull.java:224) ~[paper-1.19.jar:git-Paper-44]
103 | at org.bukkit.craftbukkit.v1_19_R1.inventory.CraftMetaSkull.<init>(CraftMetaSkull.java:58) ~[paper-1.19.jar:git-Paper-44]
104 | at jdk.internal.reflect.GeneratedConstructorAccessor50.newInstance(Unknown Source) ~[?:?]
105 | at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
106 | at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
107 | at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
108 | at org.bukkit.craftbukkit.v1_19_R1.inventory.CraftMetaItem$SerializableMeta.deserialize(CraftMetaItem.java:201) ~[paper-1.19.jar:git-Paper-44]
109 | at jdk.internal.reflect.GeneratedMethodAccessor5.invoke(Unknown Source) ~[?:?]
110 | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
111 | at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
112 | at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:85) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
113 | at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:127) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
114 | at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:207) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
115 | at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:48) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
116 | at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[snakeyaml-1.30.jar:?]
117 | at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220) ~[snakeyaml-1.30.jar:?]
118 | at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:480) ~[snakeyaml-1.30.jar:?]
119 | at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190) ~[snakeyaml-1.30.jar:?]
120 | at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:461) ~[snakeyaml-1.30.jar:?]
121 | at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556) ~[snakeyaml-1.30.jar:?]
122 | at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:39) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
123 | at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[snakeyaml-1.30.jar:?]
124 | at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220) ~[snakeyaml-1.30.jar:?]
125 | at org.bukkit.configuration.file.YamlConstructor.construct(YamlConstructor.java:27) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
126 | at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:158) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
127 | at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:156) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
128 | at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:156) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
129 | at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:156) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
130 | at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:115) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
131 | at com.nisovin.shopkeepers.util.bukkit.ConfigUtils.loadConfigSafely(ConfigUtils.java:240) ~[Shopkeepers-2.16.0.jar:?]
132 | at com.nisovin.shopkeepers.util.data.persistence.bukkit.BukkitConfigDataStore.loadFromString(BukkitConfigDataStore.java:61) ~[Shopkeepers-2.16.0.jar:?]
133 | ... 15 more
134 | [23:16:57] [Server thread/ERROR]: [Shopkeepers] Detected an issue during the loading of the saved shopkeepers data! Disabling the plugin!

</body>
</html>
[23:16:57] [Server thread/ERROR]: [Shopkeepers] Failed to load the save file! Note: Server downgrades or manually editing the save file are not supported!
com.nisovin.shopkeepers.util.data.persistence.InvalidDataFormatException: Failed to load data as Bukkit config!
	at com.nisovin.shopkeepers.util.data.persistence.bukkit.BukkitConfigDataStore.loadFromString(BukkitConfigDataStore.java:63) ~[Shopkeepers-2.16.0.jar:?]
	at com.nisovin.shopkeepers.util.data.persistence.DataStoreBase.load(DataStoreBase.java:58) ~[Shopkeepers-2.16.0.jar:?]
	at com.nisovin.shopkeepers.storage.SKShopkeeperStorage.doReload(SKShopkeeperStorage.java:456) ~[Shopkeepers-2.16.0.jar:?]
	at com.nisovin.shopkeepers.storage.SKShopkeeperStorage.reload(SKShopkeeperStorage.java:408) ~[Shopkeepers-2.16.0.jar:?]
	at com.nisovin.shopkeepers.SKShopkeepersPlugin.onEnable(SKShopkeepersPlugin.java:406) ~[Shopkeepers-2.16.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[paper-1.19.jar:git-Paper-44]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[paper-1.19.jar:git-Paper-44]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633) ~[paper-1.19.jar:git-Paper-44]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419) ~[paper-1.19.jar:git-Paper-44]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.jar:git-Paper-44]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1121) ~[paper-1.19.jar:git-Paper-44]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-44]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.bukkit.configuration.InvalidConfigurationException: Could not call method 'public static org.bukkit.inventory.meta.ItemMeta org.bukkit.craftbukkit.v1_19_R1.inventory.CraftMetaItem$SerializableMeta.deserialize(java.util.Map) throws java.lang.Throwable' of class org.bukkit.craftbukkit.v1_19_R1.inventory.CraftMetaItem$SerializableMeta for deserialization
	at com.nisovin.shopkeepers.util.bukkit.ConfigUtils.loadConfigSafely(ConfigUtils.java:247) ~[Shopkeepers-2.16.0.jar:?]
	at com.nisovin.shopkeepers.util.data.persistence.bukkit.BukkitConfigDataStore.loadFromString(BukkitConfigDataStore.java:61) ~[Shopkeepers-2.16.0.jar:?]
	... 15 more
Caused by: java.lang.IllegalArgumentException: The skull profile is missing a name or textures!
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.0.1-jre.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.profile.CraftPlayerProfile.validateSkullProfile(CraftPlayerProfile.java:38) ~[paper-1.19.jar:git-Paper-44]
	at org.bukkit.craftbukkit.v1_19_R1.inventory.CraftMetaSkull.setOwnerProfile(CraftMetaSkull.java:224) ~[paper-1.19.jar:git-Paper-44]
	at org.bukkit.craftbukkit.v1_19_R1.inventory.CraftMetaSkull.<init>(CraftMetaSkull.java:58) ~[paper-1.19.jar:git-Paper-44]
	at jdk.internal.reflect.GeneratedConstructorAccessor50.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:4[80](https://aternos.org/log/#L80)) ~[?:?]
	at org.bukkit.craftbukkit.v1_19_R1.inventory.CraftMetaItem$SerializableMeta.deserialize(CraftMetaItem.java:201) ~[paper-1.19.jar:git-Paper-44]
	at jdk.internal.reflect.GeneratedMethodAccessor5.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:[85](https://aternos.org/log/#L85)) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:127) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:207) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:48) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:480) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:1[90](https://aternos.org/log/#L90)) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:461) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556) ~[snakeyaml-1.30.jar:?]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:39) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220) ~[snakeyaml-1.30.jar:?]
	at org.bukkit.configuration.file.YamlConstructor.construct(YamlConstructor.java:27) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:158) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:156) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:156) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:156) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:[115](https://aternos.org/log/#L115)) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at com.nisovin.shopkeepers.util.bukkit.ConfigUtils.loadConfigSafely(ConfigUtils.java:240) ~[Shopkeepers-2.16.0.jar:?]
	at com.nisovin.shopkeepers.util.data.persistence.bukkit.BukkitConfigDataStore.loadFromString(BukkitConfigDataStore.java:61) ~[Shopkeepers-2.16.0.jar:?]
	... 15 more
[23:16:57] [Server thread/ERROR]: [Shopkeepers] Detected an issue during the loading of the saved shopkeepers data! Disabling the plugin!

if is a bug can you please fix it, and if just me how do i solve it?

**Comment by blablubbabc** [comment]
Your save data contains a player head item with an invalid player profile. How to deal with this issue depends on how you got into this situation, and how you want to resolve it.
Some ideas on what might have caused this issue:
* A bug in the server.
* You switched between different server versions back and forth.
* A plugin generated a player head item with a player profile that the server considers invalid / is not expecting.

Some ideas on how to resolve it:
* Revert the save.yml file to a backup.
* Search through the save.yml file for the item that is causing this and manually edit the save file to either fix the data of this item, or delete the trade, or shopkeeper involved in this.

Additionally, if this is caused by another plugin creating the invalid item in the first place:
* Contact the author of that other plugin to generate valid player head items.
* If you think that the generated item is actual valid, open a Spigot ticket to ask for Spigot's item serialization to treat it as valid.
