### ISSUE TITLE
An internal error has occurred.

### ISSUE THREAD

**Issue by blablubbabcDEV** [Shopkeepers/Shopkeepers#81]
**Migrated from:** https://dev.bukkit.org/projects/shopkeepers/issues/71

**Originally posted by DayneOram (Dec 30, 2012):** 

What steps will reproduce the problem?
1. Difficult to say, it seems to be a problem with us or our server. I simply installed it and tried to use it.
2.
3.What is the expected output? What do you see instead?
After typing /shopkeeper (like I did when I had a previous version of ShopKeepers on a previous map), I expect a shopkeeper to appear and remain still. After holding shift and right clicking the shopkeeper, I should get the extra menu as I used to.
Instead, a standard villager with a default trade setup appears, and he runs to the nearest door like a regular villager would.It also tells me "An internal error has occurred while attempting to perform this command."What version of the product are you using?1.9, as installed by Multicraft. The jar file appears to be there, as does the Shopkeepers folder. I tried removing these and then reinstalling it yet again, but the same problem occurs. Server is on 1.4.6.Do you have an error log of what happened?
30.12 16:08:36 [Server] INFO ... 22 more
30.12 16:08:36 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source)
30.12 16:08:36 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source)
30.12 16:08:36 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
30.12 16:08:36 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:70)
30.12 16:08:36 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.minecraft.server.PathfinderGoal
30.12 16:08:36 [Server] INFO ... 15 more
30.12 16:08:36 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
30.12 16:08:36 [Server] INFO at com.nisovin.shopkeepers.ShopkeepersPlugin.onCommand(ShopkeepersPlugin.java:302)
30.12 16:08:36 [Server] INFO at com.nisovin.shopkeepers.ShopkeepersPlugin.createNewAdminShopkeeper(ShopkeepersPlugin.java:332)
30.12 16:08:36 [Server] INFO at com.nisovin.shopkeepers.Shopkeeper.spawn(Shopkeeper.java:87)
30.12 16:08:36 [Server] INFO at com.nisovin.shopkeepers.shopobjects.VillagerShop.spawn(VillagerShop.java:36)
30.12 16:08:36 [Server] INFO at com.nisovin.shopkeepers.shopobjects.LivingEntityShop.spawn(LivingEntityShop.java:64)
30.12 16:08:36 [Server] INFO at com.nisovin.shopkeepers.shopobjects.VillagerShop.overwriteAI(VillagerShop.java:73)
30.12 16:08:36 [Server] INFO Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/PathfinderGoal
30.12 16:08:36 [Server] INFO at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:849)
30.12 16:08:36 [Server] INFO at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:427)
30.12 16:08:36 [Server] INFO at net.minecraft.server.v1_4_6.MinecraftServer.q(MinecraftServer.java:494)
30.12 16:08:36 [Server] INFO at net.minecraft.server.v1_4_6.DedicatedServer.r(DedicatedServer.java:224)
30.12 16:08:36 [Server] INFO at net.minecraft.server.v1_4_6.MinecraftServer.r(MinecraftServer.java:598)
30.12 16:08:36 [Server] INFO at net.minecraft.server.v1_4_6.DedicatedServerConnection.b(SourceFile:30)
30.12 16:08:36 [Server] INFO at net.minecraft.server.v1_4_6.ServerConnection.b(SourceFile:39)
30.12 16:08:36 [Server] INFO at net.minecraft.server.v1_4_6.PlayerConnection.d(PlayerConnection.java:112)
30.12 16:08:36 [Server] INFO at net.minecraft.server.v1_4_6.NetworkManager.b(NetworkManager.java:290)
30.12 16:08:36 [Server] INFO at net.minecraft.server.v1_4_6.Packet3Chat.handle(Packet3Chat.java:44)
30.12 16:08:36 [Server] INFO at net.minecraft.server.v1_4_6.PlayerConnection.a(PlayerConnection.java:853)
30.12 16:08:36 [Server] INFO at net.minecraft.server.v1_4_6.PlayerConnection.chat(PlayerConnection.java:898)
30.12 16:08:36 [Server] INFO at net.minecraft.server.v1_4_6.PlayerConnection.handleCommand(PlayerConnection.java:980)
30.12 16:08:36 [Server] INFO at org.bukkit.craftbukkit.v1_4_6.CraftServer.dispatchCommand(CraftServer.java:510)
30.12 16:08:36 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:186)
30.12 16:08:36 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
30.12 16:08:36 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'shopkeeper' in plugin Shopkeepers v1.9
30.12 16:08:36 [Server] SEVERE nullPlease provide any additional information below.

**Comment by blablubbabcDEV** [comment]
**Originally commented by DayneOram (Dec 30, 2012):** 

Nevermind, I hadn't realised that 1.9 was not for 1.4.6.

**Comment by blablubbabcDEV** [comment]
**Originally closed by DayneOram (Dec 30, 2012)**
