### ISSUE TITLE
Whenever i do /shopkeeper it says an internal error occured while trying to execute this command

### ISSUE THREAD

**Issue by Sunshine072910** [Shopkeepers/Shopkeepers#811]
## Preliminaries:

* **Shopkeepers version:** `<v2.6.0>`
* **Spigot version:** `<3553-spigot-14a2382-ef09464 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT)>`(on minehut)
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was **`<able>`** to reproduce my issue on a freshly set up and up-to-date Spigot server (currently **`<3553-spigot-14a2382-ef09464 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT>`**) with the latest version of Shopkeepers (currently **`<2.6>`**)(bc i do 1.19), with no kinds of other server or client mods(other than lunar client).

## The issue:

I used /shopkeeper and it said "an internal error occured while trying to execute this command" and didn't spawn the shopkeeper and in the console it says 
"[01:55:38] [Server thread/INFO]: SunShine072910 issued server command: /shopkeeper
[01:55:38] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'shopkeeper' in plugin Shopkeepers v2.6.0 - plugin is disabled.
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:831) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
	at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2031) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1834) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
	at net.minecraft.network.protocol.game.ServerboundChatCommandPacket.a(SourceFile:37) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
	at net.minecraft.network.protocol.game.ServerboundChatCommandPacket.a(SourceFile:13) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1150) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
	at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:131) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
	at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1129) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1122) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
	at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:140) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1106) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1014) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:291) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
	at java.lang.Thread.run(Thread.java:833) [?:?]" I am also using world edit, luck perms, and essentials spawn all on default settings. i looked in the files but i didn't see shopkeepers

**Comment by blablubbabc** [comment]
You are using an outdated plugin version: `v2.6.0` is not compatible with MC 1.19.x. You need to use Shopkeepers `v2.16.0`.

This is a known issue if you are using Minehut: They somehow configured the wrong plugin version for Minecraft 1.19. So if you are using Minehut, let them know about this issue, or search for some other way to install the correct plugin version.

**Comment by Sunshine072910** [comment]
thankyou will do
