### ISSUE TITLE
I am trying to run the plugin, I have already tried many versions and there is always such an error

### ISSUE THREAD

**Issue by ktonamot** [Shopkeepers/Shopkeepers#823]
[22:56:08 ERROR]: Could not load 'plugins\Shopkeepers-2.10.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoSuchMethodError: org.bukkit.UnsafeValues.getDataVersion()I
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[server.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:327) ~[server.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:248) [server.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:305) [server.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [server.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [server.jar:git-Spigot-79a30d7-acbc348]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_351]
Caused by: java.lang.NoSuchMethodError: org.bukkit.UnsafeValues.getDataVersion()I
        at com.nisovin.shopkeepers.storage.SKShopkeeperStorage.getMinecraftDataVersion(SKShopkeeperStorage.java:118) ~[?:?]
        at com.nisovin.shopkeepers.storage.SKShopkeeperStorage.<init>(SKShopkeeperStorage.java:112) ~[?:?]
        at com.nisovin.shopkeepers.SKShopkeepersPlugin.<init>(SKShopkeepersPlugin.java:111) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_351]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_351]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_351]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_351]
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_351]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:90) ~[server.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[server.jar:git-Spigot-79a30d7-acbc348]
        ... 6 more

**Comment by blablubbabc** [comment]
I haven't checked the version of `git-Spigot-79a30d7-acbc348`, but my guess would be that Shopkeepers v2.10.0 is not compatible with your server version. Either try an older plugin version (one being compatible with your server version), or update your server.
