### ISSUE TITLE
Shopkeepers menus dont get open

### ISSUE THREAD

**Issue by Dezaku** [Shopkeepers/Shopkeepers#888]
## Preliminaries:

* **Shopkeepers version:** `2.21`
* **Purpur version:** `Current Purpur Version: 1.21-2235-778995d (MC: 1.21)*`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## The issue:

Placed a chest with items in it like they should be. Did `/shopkeepers give`. Configured the chest via the egg and placed the villager in front of it. No trading menu gets opened by right clicking neither can I shift rightclick the shopkeeper. I also cannot place or break any blocks anymore

```[14:02:15 ERROR]: Could not pass event PlayerInteractEntityEvent to Shopkeepers v2.21.0
java.lang.NullPointerException: Cannot read field "handle" because "stack" is null
        at org.bukkit.craftbukkit.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:97) ~[purpur-1.21.jar:1.21-2235-778995d]
        at org.bukkit.craftbukkit.inventory.CraftInventory.setItem(CraftInventory.java:100) ~[purpur-1.21.jar:1.21-2235-778995d]
        at Shopkeepers-2.21.0.jar/com.nisovin.shopkeepers.ui.editor.AbstractEditorHandler.setTradeColumn(AbstractEditorHandler.java:291) ~[Shopkeepers-2.21.0.jar:?]
        at Shopkeepers-2.21.0.jar/com.nisovin.shopkeepers.ui.editor.AbstractEditorHandler.setupTradeColumns(AbstractEditorHandler.java:677) ~[Shopkeepers-2.21.0.jar:?]
        at Shopkeepers-2.21.0.jar/com.nisovin.shopkeepers.ui.editor.AbstractEditorHandler.setupCurrentPage(AbstractEditorHandler.java:659) ~[Shopkeepers-2.21.0.jar:?]
        at Shopkeepers-2.21.0.jar/com.nisovin.shopkeepers.ui.editor.AbstractEditorHandler.openWindow(AbstractEditorHandler.java:648) ~[Shopkeepers-2.21.0.jar:?]
        at Shopkeepers-2.21.0.jar/com.nisovin.shopkeepers.ui.SKUIRegistry.requestUI(SKUIRegistry.java:180) ~[Shopkeepers-2.21.0.jar:?]
        at Shopkeepers-2.21.0.jar/com.nisovin.shopkeepers.ui.SKUIRegistry.requestUI(SKUIRegistry.java:107) ~[Shopkeepers-2.21.0.jar:?]
        at Shopkeepers-2.21.0.jar/com.nisovin.shopkeepers.ui.SKUIRegistry.requestUI(SKUIRegistry.java:99) ~[Shopkeepers-2.21.0.jar:?]
        at Shopkeepers-2.21.0.jar/com.nisovin.shopkeepers.ui.SKUIRegistry.requestUI(SKUIRegistry.java:68) ~[Shopkeepers-2.21.0.jar:?]
        at Shopkeepers-2.21.0.jar/com.nisovin.shopkeepers.shopkeeper.AbstractShopkeeper.openWindow(AbstractShopkeeper.java:1431) ~[Shopkeepers-2.21.0.jar:?]
        at Shopkeepers-2.21.0.jar/com.nisovin.shopkeepers.shopkeeper.AbstractShopkeeper.openEditorWindow(AbstractShopkeeper.java:1438) ~[Shopkeepers-2.21.0.jar:?]
        at Shopkeepers-2.21.0.jar/com.nisovin.shopkeepers.shopkeeper.AbstractShopkeeper.onPlayerInteraction(AbstractShopkeeper.java:1458) ~[Shopkeepers-2.21.0.jar:?]
        at Shopkeepers-2.21.0.jar/com.nisovin.shopkeepers.shopkeeper.player.AbstractPlayerShopkeeper.onPlayerInteraction(AbstractPlayerShopkeeper.java:247) ~[Shopkeepers-2.21.0.jar:?]
        at Shopkeepers-2.21.0.jar/com.nisovin.shopkeepers.shopobjects.living.LivingEntityShopListener.onEntityInteract(LivingEntityShopListener.java:206) ~[Shopkeepers-2.21.0.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2235-778995d]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2235-778995d]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2235-778995d]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$4.performInteraction(ServerGamePacketListenerImpl.java:2798) ~[purpur-1.21.jar:1.21-2235-778995d]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$4.onInteraction(ServerGamePacketListenerImpl.java:2848) ~[purpur-1.21.jar:1.21-2235-778995d]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAction.dispatch(ServerboundInteractPacket.java:138) ~[purpur-1.21.jar:1.21-2235-778995d]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:89) ~[purpur-1.21.jar:1.21-2235-778995d]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2787) ~[purpur-1.21.jar:1.21-2235-778995d]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:76) ~[purpur-1.21.jar:1.21-2235-778995d]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:14) ~[purpur-1.21.jar:1.21-2235-778995d]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:36) ~[purpur-1.21.jar:1.21-2235-778995d]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.jar:1.21-2235-778995d]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.jar:1.21-2235-778995d]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.jar:1.21-2235-778995d]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1513) ~[purpur-1.21.jar:1.21-2235-778995d]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.jar:1.21-2235-778995d]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.jar:1.21-2235-778995d]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1491) ~[purpur-1.21.jar:1.21-2235-778995d]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1484) ~[purpur-1.21.jar:1.21-2235-778995d]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.jar:1.21-2235-778995d]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1443) ~[purpur-1.21.jar:1.21-2235-778995d]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1450) ~[purpur-1.21.jar:1.21-2235-778995d]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1295) ~[purpur-1.21.jar:1.21-2235-778995d]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332) ~[purpur-1.21.jar:1.21-2235-778995d]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]```

**Comment by blablubbabc** [comment]
This is caused by the same underlying issue as https://github.com/Shopkeepers/Shopkeepers/issues/887
