### ISSUE TITLE
Plugin crash when trade Fireworks 2 and 3 in all shop type

### ISSUE THREAD

**Issue by Arekhimself** [Shopkeepers/Shopkeepers#890]
## Preliminaries:

* **Shopkeepers version:** `2.22.0`
* **Spigot version:** `1.21R0.1`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was **able** to reproduce my issue on a freshly set up and up-to-date Spigot server 
(currently **`CraftBukkit version 4217-Spigot-146439e-68603b1 (MC: 1.21) (Implementing API version 1.21-R0.1-SNAPSHOT)`**) 
with the latest version of Shopkeepers (currently **`2.21.0 & 2.22.0`**), 
with no other plugins and with no kinds of other server or client mods.

## The issue:

Shopkeeper plugin crash when try to sell/buy or trade Firework 2 & 3 (work fine with firework 1).
crash happen at shopkeeper reload command usage or server restart
Have to manually edit save.yml to delete items and restart server

## server log

[13:49:16 INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[13:49:18 INFO]: Loaded 1290 recipes
[13:49:19 INFO]: Starting minecraft server version 1.21
[13:49:19 INFO]: Loading properties
[13:49:19 INFO]: This server is running CraftBukkit version 4217-Spigot-146439e-68603b1 (MC: 1.21) (Implementing API version 1.21-R0.1-SNAPSHOT)
[13:49:20 INFO]: Debug logging is disabled
[13:49:20 INFO]: Server Ping Player Sample Count: 12
[13:49:20 INFO]: Using 4 threads for Netty based IO
[13:49:20 INFO]: Default game type: SURVIVAL
[13:49:20 INFO]: Generating keypair
[13:49:20 INFO]: Starting Minecraft server on *:25565
[13:49:20 INFO]: Using default channel type
[13:49:21 INFO]: [Shopkeepers] Loading Shopkeepers v2.22.0
[13:49:22 INFO]: [Shopkeepers] Loaded all plugin classes (1011 ms).
[13:49:22 INFO]: [Shopkeepers] Loading config.
[13:49:22 INFO]: [Shopkeepers] Loading language file: language-en-default.yml
[13:49:22 INFO]: [Shopkeepers] Registering defaults.
[13:49:22 WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[13:49:22 WARN]: The server will make no attempt to authenticate usernames. Beware.
[13:49:22 WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[13:49:22 WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[13:49:22 INFO]: Preparing level "world"
[13:49:22 INFO]: -------- World Settings For [world] --------
[13:49:22 INFO]: Mob Spawn Range: 6
[13:49:22 INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true / Isa false
[13:49:22 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[13:49:22 INFO]: Max TNT Explosions: 100
[13:49:22 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Di 128 / Other 64
[13:49:22 INFO]: Cactus Growth Modifier: 100%
[13:49:22 INFO]: Cane Growth Modifier: 100%
[13:49:22 INFO]: Melon Growth Modifier: 100%
[13:49:22 INFO]: Mushroom Growth Modifier: 100%
[13:49:22 INFO]: Pumpkin Growth Modifier: 100%
[13:49:22 INFO]: Sapling Growth Modifier: 100%
[13:49:22 INFO]: Beetroot Growth Modifier: 100%
[13:49:22 INFO]: Carrot Growth Modifier: 100%
[13:49:22 INFO]: Potato Growth Modifier: 100%
[13:49:22 INFO]: Wheat Growth Modifier: 100%
[13:49:22 INFO]: NetherWart Growth Modifier: 100%
[13:49:22 INFO]: Vine Growth Modifier: 100%
[13:49:22 INFO]: Cocoa Growth Modifier: 100%
[13:49:22 INFO]: Bamboo Growth Modifier: 100%
[13:49:22 INFO]: SweetBerry Growth Modifier: 100%
[13:49:22 INFO]: Kelp Growth Modifier: 100%
[13:49:22 INFO]: TwistingVines Growth Modifier: 100%
[13:49:22 INFO]: WeepingVines Growth Modifier: 100%
[13:49:22 INFO]: CaveVines Growth Modifier: 100%
[13:49:22 INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Nether: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[13:49:22 INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[13:49:22 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[13:49:22 INFO]: Item Merge Radius: 2.5
[13:49:22 INFO]: Item Despawn Rate: 6000
[13:49:22 INFO]: Simulation Distance: 10
[13:49:22 INFO]: View Distance: 10
[13:49:22 INFO]: Zombie Aggressive Towards Villager: true
[13:49:22 INFO]: Nerfing mobs spawned from spawners: false
[13:49:22 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1 Hopper Can Load Chunks: false
[13:49:22 INFO]: Experience Merge Radius: 3.0
[13:49:23 INFO]: -------- World Settings For [world_nether] --------
[13:49:23 INFO]: Mob Spawn Range: 6
[13:49:23 INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true / Isa false
[13:49:23 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[13:49:23 INFO]: Max TNT Explosions: 100
[13:49:23 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Di 128 / Other 64
[13:49:23 INFO]: Cactus Growth Modifier: 100%
[13:49:23 INFO]: Cane Growth Modifier: 100%
[13:49:23 INFO]: Melon Growth Modifier: 100%
[13:49:23 INFO]: Mushroom Growth Modifier: 100%
[13:49:23 INFO]: Pumpkin Growth Modifier: 100%
[13:49:23 INFO]: Sapling Growth Modifier: 100%
[13:49:23 INFO]: Beetroot Growth Modifier: 100%
[13:49:23 INFO]: Carrot Growth Modifier: 100%
[13:49:23 INFO]: Potato Growth Modifier: 100%
[13:49:23 INFO]: Wheat Growth Modifier: 100%
[13:49:23 INFO]: NetherWart Growth Modifier: 100%
[13:49:23 INFO]: Vine Growth Modifier: 100%
[13:49:23 INFO]: Cocoa Growth Modifier: 100%
[13:49:23 INFO]: Bamboo Growth Modifier: 100%
[13:49:23 INFO]: SweetBerry Growth Modifier: 100%
[13:49:23 INFO]: Kelp Growth Modifier: 100%
[13:49:23 INFO]: TwistingVines Growth Modifier: 100%
[13:49:23 INFO]: WeepingVines Growth Modifier: 100%
[13:49:23 INFO]: CaveVines Growth Modifier: 100%
[13:49:23 INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Nether: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[13:49:23 INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[13:49:23 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[13:49:23 INFO]: Item Merge Radius: 2.5
[13:49:23 INFO]: Item Despawn Rate: 6000
[13:49:23 INFO]: Simulation Distance: 10
[13:49:23 INFO]: View Distance: 10
[13:49:23 INFO]: Zombie Aggressive Towards Villager: true
[13:49:23 INFO]: Nerfing mobs spawned from spawners: false
[13:49:23 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1 Hopper Can Load Chunks: false
[13:49:23 INFO]: Experience Merge Radius: 3.0
[13:49:23 INFO]: -------- World Settings For [world_the_end] --------
[13:49:23 INFO]: Mob Spawn Range: 6
[13:49:23 INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true / Isa false
[13:49:23 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[13:49:23 INFO]: Max TNT Explosions: 100
[13:49:23 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Di 128 / Other 64
[13:49:23 INFO]: Cactus Growth Modifier: 100%
[13:49:23 INFO]: Cane Growth Modifier: 100%
[13:49:23 INFO]: Melon Growth Modifier: 100%
[13:49:23 INFO]: Mushroom Growth Modifier: 100%
[13:49:23 INFO]: Pumpkin Growth Modifier: 100%
[13:49:23 INFO]: Sapling Growth Modifier: 100%
[13:49:23 INFO]: Beetroot Growth Modifier: 100%
[13:49:23 INFO]: Carrot Growth Modifier: 100%
[13:49:23 INFO]: Potato Growth Modifier: 100%
[13:49:23 INFO]: Wheat Growth Modifier: 100%
[13:49:23 INFO]: NetherWart Growth Modifier: 100%
[13:49:23 INFO]: Vine Growth Modifier: 100%
[13:49:23 INFO]: Cocoa Growth Modifier: 100%
[13:49:23 INFO]: Bamboo Growth Modifier: 100%
[13:49:23 INFO]: SweetBerry Growth Modifier: 100%
[13:49:23 INFO]: Kelp Growth Modifier: 100%
[13:49:23 INFO]: TwistingVines Growth Modifier: 100%
[13:49:23 INFO]: WeepingVines Growth Modifier: 100%
[13:49:23 INFO]: CaveVines Growth Modifier: 100%
[13:49:23 INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Nether: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[13:49:23 INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[13:49:23 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[13:49:23 INFO]: Item Merge Radius: 2.5
[13:49:23 INFO]: Item Despawn Rate: 6000
[13:49:23 INFO]: Simulation Distance: 10
[13:49:23 INFO]: View Distance: 10
[13:49:23 INFO]: Zombie Aggressive Towards Villager: true
[13:49:23 INFO]: Nerfing mobs spawned from spawners: false
[13:49:23 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1 Hopper Can Load Chunks: false
[13:49:23 INFO]: Experience Merge Radius: 3.0
[13:49:23 INFO]: Preparing start region for dimension minecraft:overworld
[13:49:23 INFO]: Preparing spawn area: 0%
[13:49:23 INFO]: Time elapsed: 425 ms
[13:49:24 INFO]: Preparing start region for dimension minecraft:the_nether
[13:49:24 INFO]: Preparing spawn area: 0%
[13:49:24 INFO]: Time elapsed: 178 ms
[13:49:24 INFO]: Preparing start region for dimension minecraft:the_end
[13:49:24 INFO]: Preparing spawn area: 0%
[13:49:24 INFO]: Time elapsed: 163 ms
[13:49:24 INFO]: [Shopkeepers] Enabling Shopkeepers v2.22.0
[13:49:24 INFO]: [Shopkeepers] Loading the data of 1 shopkeepers ...
[13:49:24 INFO]: Server permissions file permissions.yml is empty, ignoring it
[13:49:24 INFO]: Done (2.069s)! For help, type "help"
[13:49:28 INFO]: UUID of player Mr_F is 01a8abd5-67cd-3dce-be28-2580ffbac57e
[13:49:29 INFO]: Mr_F joined the game
[13:49:29 INFO]: Mr_F[/127.0.0.1:55823] logged in with entity id 86 at ([world]137.993217941612, 70.0, -130.60792661647932)
[13:50:25 INFO]: Mr_F issued server command: /shopkeeper reload
[13:50:25 INFO]: [Shopkeepers] Loading config.
[13:50:25 INFO]: [Shopkeepers] Loading language file: language-en-default.yml
[13:50:25 INFO]: [Shopkeepers] Registering defaults.
[13:50:25 INFO]: [Shopkeepers] Loading the data of 1 shopkeepers ...
[13:50:25 ERROR]: [Shopkeepers] Something unexpected went wrong during the loading of the saved shopkeepers data!
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "this.effects" is null
	at org.bukkit.craftbukkit.v1_21_R1.inventory.CraftMetaFirework.applyToItem(CraftMetaFirework.java:188) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4217-Spigot-146439e-68603b1]
	at org.bukkit.craftbukkit.v1_21_R1.inventory.CraftItemStack.setItemMeta(CraftItemStack.java:325) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4217-Spigot-146439e-68603b1]
	at org.bukkit.craftbukkit.v1_21_R1.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:42) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4217-Spigot-146439e-68603b1]
	at org.bukkit.craftbukkit.v1_21_R1.inventory.CraftInventory.setItem(CraftInventory.java:101) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4217-Spigot-146439e-68603b1]
	at com.nisovin.shopkeepers.util.inventory.ItemMigration.migrateItemStack(ItemMigration.java:31) ~[?:?]
	at com.nisovin.shopkeepers.util.inventory.ItemMigration.migrateItemStack(ItemMigration.java:40) ~[?:?]
	at com.nisovin.shopkeepers.shopkeeper.offers.SKPriceOffer.migrateItems(SKPriceOffer.java:254) ~[?:?]
	at com.nisovin.shopkeepers.shopkeeper.offers.SKPriceOffer.migrateOffers(SKPriceOffer.java:225) ~[?:?]
	at com.nisovin.shopkeepers.shopkeeper.player.sell.SKSellingPlayerShopkeeper$1.migrate(SKSellingPlayerShopkeeper.java:130) ~[?:?]
	at com.nisovin.shopkeepers.shopkeeper.migration.ShopkeeperDataMigrator.migrate(ShopkeeperDataMigrator.java:124) ~[?:?]
	at com.nisovin.shopkeepers.shopkeeper.migration.ShopkeeperDataMigrator.migrate(ShopkeeperDataMigrator.java:96) ~[?:?]
	at com.nisovin.shopkeepers.shopkeeper.ShopkeeperData.migrate(ShopkeeperData.java:79) ~[?:?]
	at com.nisovin.shopkeepers.storage.SKShopkeeperStorage.loadShopkeeper(SKShopkeeperStorage.java:607) ~[?:?]
	at com.nisovin.shopkeepers.storage.SKShopkeeperStorage.doReload(SKShopkeeperStorage.java:561) ~[?:?]
	at com.nisovin.shopkeepers.storage.SKShopkeeperStorage.reload(SKShopkeeperStorage.java:408) ~[?:?]
	at com.nisovin.shopkeepers.SKShopkeepersPlugin.onEnable(SKShopkeepersPlugin.java:423) ~[?:?]
	at com.nisovin.shopkeepers.SKShopkeepersPlugin.reload(SKShopkeepersPlugin.java:552) ~[?:?]
	at com.nisovin.shopkeepers.commands.shopkeepers.CommandReload.execute(CommandReload.java:34) ~[?:?]
	at com.nisovin.shopkeepers.commands.lib.Command.processCommand(Command.java:619) ~[?:?]
	at com.nisovin.shopkeepers.commands.lib.Command.processCommand(Command.java:606) ~[?:?]
	at com.nisovin.shopkeepers.commands.lib.Command.handleCommand(Command.java:509) ~[?:?]
	at com.nisovin.shopkeepers.commands.lib.BaseCommand.onCommand(BaseCommand.java:92) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:150) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_21_R1.CraftServer.dispatchCommand(CraftServer.java:913) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4217-Spigot-146439e-68603b1]
	at org.bukkit.craftbukkit.v1_21_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4217-Spigot-146439e-68603b1]
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.a(SourceFile:29) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4217-Spigot-146439e-68603b1]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(SourceFile:13) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4217-Spigot-146439e-68603b1]
	at net.minecraft.commands.execution.UnboundEntryAction.a(SourceFile:8) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4217-Spigot-146439e-68603b1]
	at net.minecraft.commands.execution.CommandQueueEntry.a(SourceFile:8) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4217-Spigot-146439e-68603b1]
	at net.minecraft.commands.execution.ExecutionContext.a(SourceFile:107) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4217-Spigot-146439e-68603b1]
	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:414) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4217-Spigot-146439e-68603b1]
	at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:336) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4217-Spigot-146439e-68603b1]
	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:323) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4217-Spigot-146439e-68603b1]
	at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:1842) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4217-Spigot-146439e-68603b1]
	at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$7(PlayerConnection.java:1818) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4217-Spigot-146439e-68603b1]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4217-Spigot-146439e-68603b1]
	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:162) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4217-Spigot-146439e-68603b1]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4217-Spigot-146439e-68603b1]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1270) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4217-Spigot-146439e-68603b1]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:203) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4217-Spigot-146439e-68603b1]
	at net.minecraft.util.thread.IAsyncTaskHandler.B(SourceFile:136) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4217-Spigot-146439e-68603b1]
	at net.minecraft.server.MinecraftServer.bv(MinecraftServer.java:1249) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4217-Spigot-146439e-68603b1]
	at net.minecraft.server.MinecraftServer.B(MinecraftServer.java:1242) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4217-Spigot-146439e-68603b1]
	at net.minecraft.util.thread.IAsyncTaskHandler.bB(SourceFile:121) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4217-Spigot-146439e-68603b1]
	at net.minecraft.server.MinecraftServer.v_(MinecraftServer.java:1213) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4217-Spigot-146439e-68603b1]
	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1078) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4217-Spigot-146439e-68603b1]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4217-Spigot-146439e-68603b1]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[13:50:25 ERROR]: [Shopkeepers] Detected an issue during the loading of the saved shopkeepers data! Disabling the plugin!
[13:50:25 INFO]: [Shopkeepers] Disabling Shopkeepers v2.22.0

**Comment by blablubbabc** [comment]
Try out the latest Spigot build: Your build is ~1 week old, and this issue has been fixed about 3 days ago.

**Comment by Arekhimself** [comment]
oh sry...
