### ISSUE TITLE
NoSuchMethodError on MC 1.21.3

### ISSUE THREAD

**Issue by SlimeDog** [Shopkeepers/Shopkeepers#929]
## Preliminaries:

* **Shopkeepers version:** `2.23.1-SNAPSHOT+1dd5b4a1`
* **Paper version:** `1.21.3-10` (but same issue on Spigot)
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Paper server:

I was **able** to reproduce my issue on a freshly set up and up-to-date Paper server (currently **`1.21.3-10`**) with the latest version of Shopkeepers (currently **`2.23.1-SNAPSHOT+ 1dd5b4a1 `**), with no other plugins and with no kinds of other server or client mods.

## The issue:

Provide a detailed description of the issue and information on how to reproduce it.

```
[09:36:06] [Server thread/INFO]: [Shopkeepers] Loading server plugin Shopkeepers v2.23.1-SNAPSHOT+1dd5b4a1
[09:36:07] [Server thread/INFO]: [Shopkeepers] Loaded all plugin classes (861 ms).
[09:36:07] [Server thread/WARN]: [Shopkeepers] Incompatible server version: 1.21.3-R0.1-SNAPSHOT (mappings: 61a218cda78417b6039da56e08194083)
[09:36:07] [Server thread/WARN]: [Shopkeepers] Shopkeepers is trying to run in 'compatibility mode'.
[09:36:07] [Server thread/INFO]: [Shopkeepers] Check for updates at: https://dev.bukkit.org/projects/shopkeepers/
[09:36:07] [Server thread/INFO]: [Shopkeepers] Loading config.
[09:36:07] [Server thread/INFO]: [Shopkeepers] Loading language file: language-en-default.yml
[09:36:07] [Server thread/INFO]: [Shopkeepers] Registering WorldGuard flag 'allow-shop'.
[09:36:07] [Server thread/INFO]: [Shopkeepers] Registering defaults.
[09:36:27] [Server thread/INFO]: [Shopkeepers] Enabling Shopkeepers v2.23.1-SNAPSHOT+1dd5b4a1
[09:36:27] [Server thread/ERROR]: Error occurred while enabling Shopkeepers v2.23.1-SNAPSHOT+1dd5b4a1 (Is it up to date?)
java.lang.NoSuchMethodError: 'void org.bukkit.inventory.meta.components.FoodComponent.setEatSeconds(float)' 
        at Shopkeepers-2.23.1-b347.jar/com.nisovin.shopkeepers.compat.ServerAssumptionsTest.createComplexItemStack(ServerAssumptionsTest.java:235) ~[Shopkeepers-2.23.1-b347.jar:?]
        at Shopkeepers-2.23.1-b347.jar/com.nisovin.shopkeepers.compat.ServerAssumptionsTest.<init>(ServerAssumptionsTest.java:160) ~[Shopkeepers-2.23.1-b347.jar:?]
        at Shopkeepers-2.23.1-b347.jar/com.nisovin.shopkeepers.compat.ServerAssumptionsTest.run(ServerAssumptionsTest.java:71) ~[Shopkeepers-2.23.1-b347.jar:?]
        at Shopkeepers-2.23.1-b347.jar/com.nisovin.shopkeepers.SKShopkeepersPlugin.onEnable(SKShopkeepersPlugin.java:326) ~[Shopkeepers-2.23.1-b347.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.3.jar:1.21.3-10-92131ad]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.3.jar:1.21.3-10-92131ad]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:643) ~[paper-1.21.3.jar:1.21.3-10-92131ad]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:592) ~[paper-1.21.3.jar:1.21.3-10-92131ad]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:767) ~[paper-1.21.3.jar:1.21.3-10-92131ad]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:529) ~[paper-1.21.3.jar:1.21.3-10-92131ad]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:326) ~[paper-1.21.3.jar:1.21.3-10-92131ad]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1233) ~[paper-1.21.3.jar:1.21.3-10-92131ad]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:339) ~[paper-1.21.3.jar:1.21.3-10-92131ad]
        at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?]
```

**Comment by blablubbabc** [comment]
Fixed with the next version: 2.23.1
