### ISSUE TITLE
Load error with Spigot build #516

### ISSUE THREAD

**Issue by blablubbabcDEV** [Shopkeepers/Shopkeepers#99]
**Migrated from:** https://dev.bukkit.org/projects/shopkeepers/issues/89

**Originally posted by diannetea (Feb 12, 2013):** 

2013-02-12 00:49:34 [SEVERE] Error occurred while enabling Shopkeepers v1.11 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_4_R1/entity/CraftVillager
Â  Â  at com.nisovin.shopkeepers.volatilecode.VolatileCode_1_4_7.overwriteVillagerAI(VolatileCode_1_4_7.java:78)
Â  Â  at com.nisovin.shopkeepers.shopobjects.VillagerShop.overwriteAI(VillagerShop.java:73)
Â  Â  at com.nisovin.shopkeepers.shopobjects.LivingEntityShop.spawn(LivingEntityShop.java:63)
Â  Â  at com.nisovin.shopkeepers.shopobjects.VillagerShop.spawn(VillagerShop.java:36)
Â  Â  at com.nisovin.shopkeepers.Shopkeeper.spawn(Shopkeeper.java:87)
Â  Â  at com.nisovin.shopkeepers.ShopkeepersPlugin.loadShopkeepersInChunk(ShopkeepersPlugin.java:579)
Â  Â  at com.nisovin.shopkeepers.ShopkeepersPlugin.onEnable(ShopkeepersPlugin.java:114)
Â  Â  at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
Â  Â  at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:457)
Â  Â  at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:383)
Â  Â  at org.bukkit.craftbukkit.v1_4_R1.v1_4_R1.CraftServer.loadPlugin(CraftServer.java:308)
Â  Â  at org.bukkit.craftbukkit.v1_4_R1.v1_4_R1.CraftServer.enablePlugins(CraftServer.java:290)
Â  Â  at net.minecraft.server.v1_4_R1.v1_4_R1.MinecraftServer.j(MinecraftServer.java:327)
Â  Â  at net.minecraft.server.v1_4_R1.v1_4_R1.MinecraftServer.e(MinecraftServer.java:306)
Â  Â  at net.minecraft.server.v1_4_R1.v1_4_R1.MinecraftServer.a(MinecraftServer.java:265)
Â  Â  at net.minecraft.server.v1_4_R1.v1_4_R1.DedicatedServer.init(DedicatedServer.java:149)
Â  Â  at net.minecraft.server.v1_4_R1.v1_4_R1.MinecraftServer.run(MinecraftServer.java:405)
Â  Â  at net.minecraft.server.v1_4_R1.v1_4_R1.ThreadServerApplication.run(SourceFile:849)
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_4_R1.entity.CraftVillager
Â  Â  at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:70)
Â  Â  at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
Â  Â  at java.lang.ClassLoader.loadClass(Unknown Source)
Â  Â  at java.lang.ClassLoader.loadClass(Unknown Source)
Â  Â  ... 18 more

**Comment by blablubbabcDEV** [comment]
**Originally commented by nisovin (Feb 12, 2013):** 

Seems to be a Spigot problem, not a Shopkeepers problem.

**Comment by blablubbabcDEV** [comment]
**Originally commented by Endless123 (Feb 21, 2013):** 

2013-02-21 12:54:42 [INFO] [Shopkeepers] Enabling Shopkeepers v1.10.0
2013-02-21 12:54:42 [SEVERE] [Shopkeepers] Incompatible server version: Shopkeepers plugin cannot be enabled.
:( is there no way to get this plugin working with spigot? it used to work before - i dont get any errors other then this one.

**Comment by blablubbabcDEV** [comment]
**Originally closed by nisovin (Mar 18, 2013)**
